=== vessellook/quiestioningBot/code/krasoteevo/tests/schema2.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "first version of schema of JSON format used by krasoteevo.ru",
  "type": "object",
  "properties": {
    "sentence": {
      "type": "string"
    },
    "tokens": {
      "type": "array",
      "description": "array of words",
      "items": {
        "type": "string"
      }
    },
    "morphs": {
      "type": "array",
      "description": "array of morph info lists",
      "items": {
        "type": "object",
        "description": "info about each token",
        "properties": {
          "index": {
            "type": "integer",
            "minimum": 0
          },
          "token": {
            "type": "string"
          },
          "lower": {
            "type": "string"
          },
          "homonyms": {
            "type": "array",
            "items": {
              "type": "object",
              "description": "morph info",
              "properties": {
                "index": {
                  "type": "integer",
                  "minimum": 0
                },
                "word": {
                  "type": "string"
                },
                "lexem": {
                  "type": "string"
                },
                "tags": {
                  "type": "string",
                  "pattern": "^OpencorporaTag\\('[A-Za-z ,0-9]+'\\)$"
                },
                "active": {
                  "type": "boolean"
                }
              }
            }
          },
          "banned_cases": {
            "type": "array"
          },
          "features": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "synts": {
      "type": "array",
      "description": "array of links between tokens",
      "items": {
        "type": "object",
        "properties": {
          "dep_type": {
            "type": "string"
          },
          "head": {
            "type": "string"
          },
          "dependent": {
            "type": "string"
          },
          "head_i": {
            "type": "integer",
            "minimum": 0
          },
          "dependent_i": {
            "type": "integer",
            "minimum": 0
          },
          "head_homonym_i": {
            "type": "integer",
            "minimum": 0
          },
          "dependent_homonym_i": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    }
  }
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/335.json
{
  "sentence": "Приданого тоже никакого, да он на приданое и не стал бы рассчитывать...",
  "tokens": [
    "Приданого",
    "тоже",
    "никакого",
    ",",
    "да",
    "он",
    "на",
    "приданое",
    "и",
    "не",
    "стал",
    "бы",
    "рассчитывать",
    "..."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "Приданого",
      "homonyms": [
        {
          "index": 0,
          "word": "приданого",
          "lexem": "приданое",
          "tags": "S ЕД СР РОД НЕОД",
          "active": true
        }
      ]
    },
    {
      "index": 1,
      "token": "тоже",
      "homonyms": [
        {
          "index": 0,
          "word": "тоже",
          "lexem": "тоже",
          "tags": "PART",
          "active": false
        }
      ]
    },
    {
      "index": 2,
      "token": "никакого",
      "homonyms": [
        {
          "index": 0,
          "word": "никакого",
          "lexem": "никакой",
          "tags": "A ЕД СР РОД",
          "active": true
        },
        {
          "index": 1,
          "word": "никакого",
          "lexem": "никакой",
          "tags": "A ЕД МУЖ РОД",
          "active": false
        },
        {
          "index": 2,
          "word": "никакого",
          "lexem": "никакой",
          "tags": "A ЕД МУЖ ВИН",
          "active": false
        }
      ]
    },
    {
      "index": 3,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 4,
      "token": "да",
      "homonyms": [
        {
          "index": 0,
          "word": "да",
          "lexem": "да",
          "tags": "PART",
          "active": false
        },
        {
          "index": 1,
          "word": "да",
          "lexem": "да",
          "tags": "CONJ",
          "active": false
        },
        {
          "index": 2,
          "word": "да",
          "lexem": "да",
          "tags": "INTJ",
          "active": false
        }
      ]
    },
    {
      "index": 5,
      "token": "он",
      "homonyms": [
        {
          "index": 0,
          "word": "он",
          "lexem": "он",
          "tags": "S ЕД МУЖ ИМ",
          "active": true
        }
      ]
    },
    {
      "index": 6,
      "token": "на",
      "homonyms": [
        {
          "index": 0,
          "word": "на",
          "lexem": "на",
          "tags": "PR",
          "active": true
        },
        {
          "index": 1,
          "word": "на",
          "lexem": "на",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "на",
          "lexem": "на",
          "tags": "INTJ",
          "active": false
        }
      ]
    },
    {
      "index": 7,
      "token": "приданое",
      "homonyms": [
        {
          "index": 0,
          "word": "приданое",
          "lexem": "приданое",
          "tags": "S ЕД СР ИМ НЕОД",
          "active": false
        },
        {
          "index": 1,
          "word": "приданое",
          "lexem": "приданое",
          "tags": "S ЕД СР ВИН НЕОД",
          "active": true
        }
      ]
    },
    {
      "index": 8,
      "token": "и",
      "homonyms": [
        {
          "index": 0,
          "word": "и",
          "lexem": "и",
          "tags": "CONJ",
          "active": true
        },
        {
          "index": 1,
          "word": "и",
          "lexem": "и",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "и",
          "lexem": "и",
          "tags": "INTJ",
          "active": false
        },
        {
          "index": 3,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 4,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 5,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 6,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 7,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 8,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 9,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 10,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 11,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 12,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 13,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 14,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ПР ОД",
          "active": false
        }
      ]
    },
    {
      "index": 9,
      "token": "не",
      "homonyms": [
        {
          "index": 0,
          "word": "не",
          "lexem": "не",
          "tags": "PART",
          "active": true
        }
      ]
    },
    {
      "index": 10,
      "token": "стал",
      "homonyms": [
        {
          "index": 0,
          "word": "стал",
          "lexem": "стать",
          "tags": "V ЕД СОВ ПРОШ ИЗЪЯВ",
          "active": true
        }
      ]
    },
    {
      "index": 11,
      "token": "бы",
      "homonyms": [
        {
          "index": 0,
          "word": "бы",
          "lexem": "бы",
          "tags": "PART",
          "active": true
        }
      ]
    },
    {
      "index": 12,
      "token": "рассчитывать",
      "homonyms": [
        {
          "index": 0,
          "word": "рассчитывать",
          "lexem": "рассчитывать",
          "tags": "V ИНФ НЕСОВ",
          "active": true
        },
        {
          "index": 1,
          "word": "рассчитывать",
          "lexem": "рассчитывать",
          "tags": "V ИНФ НЕСОВ",
          "active": true
        }
      ]
    },
    {
      "index": 13,
      "token": "...",
      "homonyms": [
        {
          "index": 0,
          "word": "...",
          "lexem": "...",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "опред",
      "head": "приданого",
      "dependent": "никакого",
      "head_i": 0,
      "head_homonym_i": 0,
      "dependent_i": 2,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предл",
      "head": "на",
      "dependent": "приданое",
      "head_i": 6,
      "head_homonym_i": 0,
      "dependent_i": 7,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "огранич",
      "head": "стал",
      "dependent": "не",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 9,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "аналит",
      "head": "стал",
      "dependent": "бы",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 11,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "стал",
      "dependent": "он",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 5,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "несобст-агент",
      "head": "стал",
      "dependent": "приданого",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 0,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "стал",
      "dependent": "на",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "соч-союзн",
      "head": "и",
      "dependent": "стал",
      "head_i": 8,
      "head_homonym_i": 0,
      "dependent_i": 10,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "сочин",
      "head": "приданое",
      "dependent": "и",
      "head_i": 7,
      "head_homonym_i": 1,
      "dependent_i": 8,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "обст",
      "head": "стал",
      "dependent": "на",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "обст",
      "head": "стал",
      "dependent": "рассчитывать",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 12,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "обст",
      "head": "стал",
      "dependent": "рассчитывать",
      "head_i": 10,
      "head_homonym_i": 0,
      "dependent_i": 12,
      "dependent_homonym_i": 1
    }
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/216.json
{
  "sentence": "Разумихин донес ему, что тот спит, как сурок.",
  "tokens": [
    "Разумихин",
    "донес",
    "ему",
    ",",
    "что",
    "тот",
    "спит",
    ",",
    "как",
    "сурок",
    "."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "Разумихин",
      "homonyms": [
        {
          "index": 0,
          "word": "разумихин",
          "lexem": "разумихин",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": true
        }
      ]
    },
    {
      "index": 1,
      "token": "донес",
      "homonyms": [
        {
          "index": 0,
          "word": "донёс",
          "lexem": "донести",
          "tags": "V ЕД СОВ ПРОШ ИЗЪЯВ",
          "active": true
        }
      ]
    },
    {
      "index": 2,
      "token": "ему",
      "homonyms": [
        {
          "index": 0,
          "word": "ему",
          "lexem": "он",
          "tags": "S ЕД МУЖ ДАТ",
          "active": true
        },
        {
          "index": 1,
          "word": "ему",
          "lexem": "оно",
          "tags": "S ЕД СР ДАТ",
          "active": false
        }
      ]
    },
    {
      "index": 3,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 4,
      "token": "что",
      "homonyms": [
        {
          "index": 0,
          "word": "что",
          "lexem": "что",
          "tags": "CONJ",
          "active": false
        },
        {
          "index": 1,
          "word": "что",
          "lexem": "что",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "что",
          "lexem": "что",
          "tags": "S ЕД СР ВИН",
          "active": false
        },
        {
          "index": 3,
          "word": "что",
          "lexem": "что",
          "tags": "S ЕД СР ИМ",
          "active": true
        },
        {
          "index": 4,
          "word": "что",
          "lexem": "что",
          "tags": "ADV",
          "active": false
        }
      ]
    },
    {
      "index": 5,
      "token": "тот",
      "homonyms": [
        {
          "index": 0,
          "word": "тот",
          "lexem": "тот",
          "tags": "A ЕД МУЖ ИМ",
          "active": true
        },
        {
          "index": 1,
          "word": "тот",
          "lexem": "тот",
          "tags": "A ЕД МУЖ ВИН",
          "active": true
        }
      ]
    },
    {
      "index": 6,
      "token": "спит",
      "homonyms": [
        {
          "index": 0,
          "word": "спит",
          "lexem": "спать",
          "tags": "V ЕД НЕСОВ НЕПРОШ ИЗЪЯВ 3-Л",
          "active": true
        },
        {
          "index": 1,
          "word": "спит",
          "lexem": "спить",
          "tags": "V ПРИЧ КР ЕД МУЖ",
          "active": true
        }
      ]
    },
    {
      "index": 7,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 8,
      "token": "как",
      "homonyms": [
        {
          "index": 0,
          "word": "как",
          "lexem": "как",
          "tags": "CONJ",
          "active": false
        },
        {
          "index": 1,
          "word": "как",
          "lexem": "как",
          "tags": "ADV",
          "active": false
        },
        {
          "index": 2,
          "word": "как",
          "lexem": "как",
          "tags": "PART",
          "active": false
        }
      ]
    },
    {
      "index": 9,
      "token": "сурок",
      "homonyms": [
        {
          "index": 0,
          "word": "сурок",
          "lexem": "сурок",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": true
        }
      ]
    },
    {
      "index": 10,
      "token": ".",
      "homonyms": [
        {
          "index": 0,
          "word": ".",
          "lexem": ".",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "предик",
      "head": "донёс",
      "dependent": "разумихин",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 0,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "спит",
      "dependent": "что",
      "head_i": 6,
      "head_homonym_i": 0,
      "dependent_i": 4,
      "dependent_homonym_i": 3
    },
    {
      "dep_type": "предик",
      "head": "спит",
      "dependent": "сурок",
      "head_i": 6,
      "head_homonym_i": 0,
      "dependent_i": 9,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "спит",
      "dependent": "сурок",
      "head_i": 6,
      "head_homonym_i": 1,
      "dependent_i": 9,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "донёс",
      "dependent": "ему",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 2,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "донёс",
      "dependent": "тот",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 5,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "1-компл",
      "head": "спит",
      "dependent": "тот",
      "head_i": 6,
      "head_homonym_i": 0,
      "dependent_i": 5,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "спит",
      "dependent": "тот",
      "head_i": 6,
      "head_homonym_i": 0,
      "dependent_i": 5,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "1-компл",
      "head": "спит",
      "dependent": "тот",
      "head_i": 6,
      "head_homonym_i": 1,
      "dependent_i": 5,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "спит",
      "dependent": "тот",
      "head_i": 6,
      "head_homonym_i": 1,
      "dependent_i": 5,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "релят",
      "head": "ему",
      "dependent": "спит",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "релят",
      "head": "ему",
      "dependent": "спит",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 1
    }
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/92.json
{
  "sentence": "А там, во дворе, уже запрягают лошадей.",
  "tokens": [
    "А",
    "там",
    ",",
    "во",
    "дворе",
    ",",
    "уже",
    "запрягают",
    "лошадей",
    "."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "А",
      "homonyms": [
        {
          "index": 0,
          "word": "а",
          "lexem": "а",
          "tags": "CONJ",
          "active": true
        },
        {
          "index": 1,
          "word": "а",
          "lexem": "а",
          "tags": "INTJ",
          "active": false
        },
        {
          "index": 2,
          "word": "а",
          "lexem": "а",
          "tags": "PART",
          "active": false
        },
        {
          "index": 3,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 4,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 5,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 6,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 7,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 8,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 9,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 10,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 11,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 12,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 13,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 14,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        },
        {
          "index": 15,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 16,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 17,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 18,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 19,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 20,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 21,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 22,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 23,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 24,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 25,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 26,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        }
      ]
    },
    {
      "index": 1,
      "token": "там",
      "homonyms": [
        {
          "index": 0,
          "word": "там",
          "lexem": "там",
          "tags": "ADV",
          "active": false
        },
        {
          "index": 1,
          "word": "там",
          "lexem": "там",
          "tags": "PART",
          "active": false
        }
      ]
    },
    {
      "index": 2,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 3,
      "token": "во",
      "homonyms": [
        {
          "index": 0,
          "word": "во",
          "lexem": "в",
          "tags": "PR",
          "active": true
        }
      ]
    },
    {
      "index": 4,
      "token": "дворе",
      "homonyms": [
        {
          "index": 0,
          "word": "дворе",
          "lexem": "двор",
          "tags": "S ЕД МУЖ ПР НЕОД",
          "active": true
        }
      ]
    },
    {
      "index": 5,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 6,
      "token": "уже",
      "homonyms": [
        {
          "index": 0,
          "word": "уже",
          "lexem": "уже",
          "tags": "ADV",
          "active": true
        },
        {
          "index": 1,
          "word": "уже",
          "lexem": "уже",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "уже",
          "lexem": "уж",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": true
        },
        {
          "index": 3,
          "word": "уже",
          "lexem": "узкий",
          "tags": "A СРАВ",
          "active": true
        }
      ]
    },
    {
      "index": 7,
      "token": "запрягают",
      "homonyms": [
        {
          "index": 0,
          "word": "запрягают",
          "lexem": "запрягать",
          "tags": "V МН НЕСОВ НЕПРОШ ИЗЪЯВ 3-Л",
          "active": true
        }
      ]
    },
    {
      "index": 8,
      "token": "лошадей",
      "homonyms": [
        {
          "index": 0,
          "word": "лошадей",
          "lexem": "лошадь",
          "tags": "S МН ЖЕН РОД ОД",
          "active": true
        },
        {
          "index": 1,
          "word": "лошадей",
          "lexem": "лошадь",
          "tags": "S МН ЖЕН ВИН ОД",
          "active": true
        }
      ]
    },
    {
      "index": 9,
      "token": ".",
      "homonyms": [
        {
          "index": 0,
          "word": ".",
          "lexem": ".",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "предл",
      "head": "во",
      "dependent": "дворе",
      "head_i": 3,
      "head_homonym_i": 0,
      "dependent_i": 4,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "об-аппоз",
      "head": "дворе",
      "dependent": "уже",
      "head_i": 4,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 2
    },
    {
      "dep_type": "1-компл",
      "head": "запрягают",
      "dependent": "во",
      "head_i": 7,
      "head_homonym_i": 0,
      "dependent_i": 3,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "запрягают",
      "dependent": "лошадей",
      "head_i": 7,
      "head_homonym_i": 0,
      "dependent_i": 8,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "соч-союзн",
      "head": "а",
      "dependent": "уже",
      "head_i": 0,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 3
    },
    {
      "dep_type": "соч-союзн",
      "head": "а",
      "dependent": "дворе",
      "head_i": 0,
      "head_homonym_i": 0,
      "dependent_i": 4,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "соч-союзн",
      "head": "а",
      "dependent": "уже",
      "head_i": 0,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 2
    },
    {
      "dep_type": "соч-союзн",
      "head": "а",
      "dependent": "лошадей",
      "head_i": 0,
      "head_homonym_i": 0,
      "dependent_i": 8,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "соч-союзн",
      "head": "а",
      "dependent": "лошадей",
      "head_i": 0,
      "head_homonym_i": 0,
      "dependent_i": 8,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "обст",
      "head": "запрягают",
      "dependent": "уже",
      "head_i": 7,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    }
  ]
}
