=== vessellook/quiestioningBot/code/krasoteevo/tests/schema1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "first version of schema of JSON format used by krasoteevo.ru",
  "type": "object",
  "properties": {
    "sentence": {
      "type": "string"
    },
    "tokens": {
      "type": "array",
      "description": "array of words",
      "items": {
        "type": "string"
      }
    },
    "morphs": {
      "type": "array",
      "description": "array of morph info lists",
      "items": {
        "type": "array",
        "description": "morph info list",
        "items": {
          "type": "object",
          "description": "morph info",
          "properties": {
            "word": {
              "type": "string"
            },
            "lexem": {
              "type": "string"
            },
            "tags": {
              "type": "string",
              "pattern": "^OpencorporaTag\\('[A-Za-z ,0-9]+'\\)$"
            }
          }
        }
      }
    },
    "synts": {
      "type": "array",
      "description": "array of links between tokens",
      "items": {
        "type": "array",
        "description": "link between tokens",
        "items": [
          {
            "type": "integer",
            "description": "source[main] token index"
          },
          {
            "type": "integer",
            "description": "target[dependent] token index"
          },
          {
            "type": "string",
            "description": "link's syntax type"
          },
          {
            "type": "string",
            "description": "source[main] token"
          },
          {
            "type": "string",
            "description": "target[dependent] token"
          }
        ]
      }
    }
  }
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/277.json
{
  "sentence": "Рассказ его жадно слушали; но когда он думал, что уже кончил и удовлетворил своих слушательниц, то оказалось, что для них он как будто еще и не начинал.",
  "tokens": [
    "Рассказ",
    "его",
    "жадно",
    "слушали",
    ";",
    "но",
    "когда",
    "он",
    "думал",
    ",",
    "что",
    "уже",
    "кончил",
    "и",
    "удовлетворил",
    "своих",
    "слушательниц",
    ",",
    "то",
    "оказалось",
    ",",
    "что",
    "для",
    "них",
    "он",
    "как",
    "будто",
    "еще",
    "и",
    "не",
    "начинал",
    "."
  ],
  "morphs": [
    [
      {
        "word": "рассказ",
        "lexem": "рассказ",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,accs')"
      }
    ],
    [
      {
        "word": "его",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,gent')"
      }
    ],
    [
      {
        "word": "жадно",
        "lexem": "жадно",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [
      {
        "word": "слушали",
        "lexem": "слушать",
        "tags": "OpencorporaTag('VERB,impf,tran plur,past,indc')"
      }
    ],
    [],
    [
      {
        "word": "но",
        "lexem": "но",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [
      {
        "word": "думал",
        "lexem": "думать",
        "tags": "OpencorporaTag('VERB,impf,intr masc,sing,past,indc')"
      },
      {
        "word": "думал",
        "lexem": "думать",
        "tags": "OpencorporaTag('VERB,impf,tran masc,sing,past,indc')"
      }
    ],
    [],
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,nomn')"
      }
    ],
    [
      {
        "word": "уже",
        "lexem": "уже",
        "tags": "OpencorporaTag('ADVB')"
      },
      {
        "word": "уже",
        "lexem": "узкий",
        "tags": "OpencorporaTag('COMP,Qual')"
      }
    ],
    [
      {
        "word": "кончил",
        "lexem": "кончить",
        "tags": "OpencorporaTag('VERB,perf,tran masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "удовлетворил",
        "lexem": "удовлетворить",
        "tags": "OpencorporaTag('VERB,perf,tran masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "своих",
        "lexem": "свой",
        "tags": "OpencorporaTag('ADJF,Apro,Anph plur,gent')"
      },
      {
        "word": "своих",
        "lexem": "свой",
        "tags": "OpencorporaTag('ADJF,Apro,Anph anim,plur,accs')"
      }
    ],
    [
      {
        "word": "слушательниц",
        "lexem": "слушательница",
        "tags": "OpencorporaTag('NOUN,anim,femn plur,accs')"
      }
    ],
    [],
    [
      {
        "word": "то",
        "lexem": "тот",
        "tags": "OpencorporaTag('ADJF,Subx,Apro,Anph neut,sing,nomn')"
      }
    ],
    [
      {
        "word": "оказалось",
        "lexem": "оказаться",
        "tags": "OpencorporaTag('VERB,perf,intr neut,sing,past,indc')"
      }
    ],
    [],
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,nomn')"
      }
    ],
    [
      {
        "word": "для",
        "lexem": "длить",
        "tags": "OpencorporaTag('GRND,impf,tran pres')"
      }
    ],
    [
      {
        "word": "них",
        "lexem": "они",
        "tags": "OpencorporaTag('NPRO,3per,Anph plur,gent,Af-p')"
      },
      {
        "word": "них",
        "lexem": "они",
        "tags": "OpencorporaTag('NPRO,3per,Anph plur,loct,Af-p')"
      },
      {
        "word": "них",
        "lexem": "они",
        "tags": "OpencorporaTag('NPRO,3per,Anph plur,accs,Af-p')"
      }
    ],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [],
    [],
    [
      {
        "word": "ещё",
        "lexem": "ещё",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "не",
        "lexem": "не",
        "tags": "OpencorporaTag('PRCL')"
      }
    ],
    [
      {
        "word": "начинал",
        "lexem": "начинать",
        "tags": "OpencorporaTag('VERB,impf,tran masc,sing,past,indc')"
      }
    ],
    []
  ],
  "synts": [
    [
      30,
      29,
      "огранич",
      "начинал",
      "не"
    ],
    [
      19,
      22,
      "обст",
      "оказалось",
      "для"
    ],
    [
      0,
      1,
      "атриб",
      "рассказ",
      "его"
    ],
    [
      8,
      7,
      "предик",
      "думал",
      "он"
    ],
    [
      11,
      10,
      "предик",
      "уже",
      "что"
    ],
    [
      19,
      21,
      "предик",
      "оказалось",
      "что"
    ],
    [
      3,
      0,
      "1-компл",
      "слушали",
      "рассказ"
    ],
    [
      14,
      15,
      "1-компл",
      "удовлетворил",
      "своих"
    ],
    [
      14,
      15,
      "1-компл",
      "удовлетворил",
      "своих"
    ],
    [
      14,
      16,
      "1-компл",
      "удовлетворил",
      "слушательниц"
    ],
    [
      21,
      24,
      "подч-союзн",
      "что",
      "он"
    ],
    [
      13,
      14,
      "соч-союзн",
      "и",
      "удовлетворил"
    ],
    [
      28,
      30,
      "соч-союзн",
      "и",
      "начинал"
    ],
    [
      14,
      19,
      "сочин",
      "удовлетворил",
      "оказалось"
    ],
    [
      3,
      5,
      "сочин",
      "слушали",
      "но"
    ],
    [
      12,
      13,
      "сочин",
      "кончил",
      "и"
    ],
    [
      19,
      28,
      "сочин",
      "оказалось",
      "и"
    ],
    [
      3,
      2,
      "обст",
      "слушали",
      "жадно"
    ],
    [
      12,
      11,
      "обст",
      "кончил",
      "уже"
    ],
    [
      22,
      27,
      "обст",
      "для",
      "ещё"
    ],
    [
      19,
      23,
      "присвяз",
      "оказалось",
      "них"
    ],
    [
      19,
      23,
      "присвяз",
      "оказалось",
      "них"
    ],
    [
      19,
      23,
      "присвяз",
      "оказалось",
      "них"
    ],
    [
      19,
      18,
      "сент-предик",
      "оказалось",
      "то"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/98.json
{
  "sentence": "А лошади уже стоят у крыльца.",
  "tokens": [
    "А",
    "лошади",
    "уже",
    "стоят",
    "у",
    "крыльца",
    "."
  ],
  "morphs": [
    [
      {
        "word": "а",
        "lexem": "а",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "лошади",
        "lexem": "лошадь",
        "tags": "OpencorporaTag('NOUN,anim,femn plur,nomn')"
      }
    ],
    [
      {
        "word": "уже",
        "lexem": "узкий",
        "tags": "OpencorporaTag('COMP,Qual')"
      }
    ],
    [
      {
        "word": "стоят",
        "lexem": "стоять",
        "tags": "OpencorporaTag('VERB,impf,intr plur,3per,pres,indc')"
      },
      {
        "word": "стоят",
        "lexem": "стоить",
        "tags": "OpencorporaTag('VERB,impf,tran plur,3per,pres,indc')"
      }
    ],
    [
      {
        "word": "у",
        "lexem": "у",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "крыльца",
        "lexem": "крыльцо",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,gent')"
      },
      {
        "word": "крыльца",
        "lexem": "крыльцо",
        "tags": "OpencorporaTag('NOUN,inan,neut plur,accs')"
      }
    ],
    []
  ],
  "synts": [
    [
      4,
      5,
      "предл",
      "у",
      "крыльца"
    ],
    [
      4,
      5,
      "предл",
      "у",
      "крыльца"
    ],
    [
      2,
      1,
      "предик",
      "уже",
      "лошади"
    ],
    [
      3,
      4,
      "1-компл",
      "стоят",
      "у"
    ],
    [
      0,
      2,
      "соч-союзн",
      "а",
      "уже"
    ],
    [
      3,
      4,
      "обст",
      "стоят",
      "у"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/7.json
{
  "sentence": "Что сделать, чем помочь?",
  "tokens": [
    "Что",
    "сделать",
    ",",
    "чем",
    "помочь",
    "?"
  ],
  "morphs": [
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,accs')"
      }
    ],
    [
      {
        "word": "сделать",
        "lexem": "сделать",
        "tags": "OpencorporaTag('INFN,perf,tran')"
      }
    ],
    [],
    [
      {
        "word": "чем",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,ablt')"
      }
    ],
    [
      {
        "word": "помочь",
        "lexem": "помочь",
        "tags": "OpencorporaTag('INFN,perf,intr')"
      },
      {
        "word": "помочь",
        "lexem": "помочь",
        "tags": "OpencorporaTag('NOUN,inan,femn,Arch sing,nomn')"
      }
    ],
    []
  ],
  "synts": [
    [
      4,
      3,
      "агент",
      "помочь",
      "чем"
    ],
    [
      1,
      0,
      "1-компл",
      "сделать",
      "что"
    ],
    [
      3,
      4,
      "подч-союзн",
      "чем",
      "помочь"
    ],
    [
      3,
      4,
      "подч-союзн",
      "чем",
      "помочь"
    ],
    [
      3,
      4,
      "инф-союзн",
      "чем",
      "помочь"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/222.json
{
  "sentence": "Не знаешь, он к тем пойдет, али те сюда придут?",
  "tokens": [
    "Не",
    "знаешь",
    ",",
    "он",
    "к",
    "тем",
    "пойдет",
    ",",
    "али",
    "те",
    "сюда",
    "придут",
    "?"
  ],
  "morphs": [
    [],
    [
      {
        "word": "знаешь",
        "lexem": "знать",
        "tags": "OpencorporaTag('VERB,impf,tran sing,2per,pres,indc')"
      }
    ],
    [],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [
      {
        "word": "к",
        "lexem": "к",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "тем",
        "lexem": "тот",
        "tags": "OpencorporaTag('ADJF,Subx,Apro,Anph masc,sing,ablt')"
      }
    ],
    [
      {
        "word": "пойдёт",
        "lexem": "пойти",
        "tags": "OpencorporaTag('VERB,perf,intr sing,3per,futr,indc')"
      }
    ],
    [],
    [],
    [
      {
        "word": "те",
        "lexem": "ты",
        "tags": "OpencorporaTag('NPRO,2per sing,datv,Arch')"
      }
    ],
    [
      {
        "word": "сюда",
        "lexem": "сюда",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [
      {
        "word": "придут",
        "lexem": "прийти",
        "tags": "OpencorporaTag('VERB,perf,intr plur,3per,futr,indc')"
      }
    ],
    []
  ],
  "synts": [
    [
      6,
      3,
      "предик",
      "пойдёт",
      "он"
    ],
    [
      6,
      4,
      "1-компл",
      "пойдёт",
      "к"
    ],
    [
      6,
      5,
      "1-компл",
      "пойдёт",
      "тем"
    ],
    [
      11,
      9,
      "1-компл",
      "придут",
      "те"
    ],
    [
      6,
      11,
      "сочин",
      "пойдёт",
      "придут"
    ],
    [
      11,
      10,
      "обст",
      "придут",
      "сюда"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/42.json
{
  "sentence": "Сальная свеча пылала дрожащим хмурым пламенем.",
  "tokens": [
    "Сальная",
    "свеча",
    "пылала",
    "дрожащим",
    "хмурым",
    "пламенем",
    "."
  ],
  "morphs": [
    [
      {
        "word": "сальная",
        "lexem": "сальный",
        "tags": "OpencorporaTag('ADJF,Qual femn,sing,nomn')"
      }
    ],
    [
      {
        "word": "свеча",
        "lexem": "свеча",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,nomn')"
      }
    ],
    [
      {
        "word": "пылала",
        "lexem": "пылать",
        "tags": "OpencorporaTag('VERB,impf,intr femn,sing,past,indc')"
      }
    ],
    [
      {
        "word": "дрожащим",
        "lexem": "дрожать",
        "tags": "OpencorporaTag('PRTF,impf,intr,pres,actv neut,sing,ablt')"
      }
    ],
    [
      {
        "word": "хмурым",
        "lexem": "хмурый",
        "tags": "OpencorporaTag('ADJF,Qual neut,sing,ablt')"
      }
    ],
    [
      {
        "word": "пламенем",
        "lexem": "пламя",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,ablt')"
      }
    ],
    []
  ],
  "synts": [
    [
      1,
      0,
      "опред",
      "свеча",
      "сальная"
    ],
    [
      5,
      3,
      "опред",
      "пламенем",
      "дрожащим"
    ],
    [
      5,
      4,
      "опред",
      "пламенем",
      "хмурым"
    ],
    [
      2,
      5,
      "агент",
      "пылала",
      "пламенем"
    ],
    [
      2,
      1,
      "предик",
      "пылала",
      "свеча"
    ],
    [
      3,
      5,
      "1-компл",
      "дрожащим",
      "пламенем"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/95.json
{
  "sentence": "И отец, огромный, толстый от медвежьей шубы, надетой поверх полушубка, в черных, выше колен, валенках и в большой боярской шапке, сядет на диван и скажет;",
  "tokens": [
    "И",
    "отец",
    ",",
    "огромный",
    ",",
    "толстый",
    "от",
    "медвежьей",
    "шубы",
    ",",
    "надетой",
    "поверх",
    "полушубка",
    ",",
    "в",
    "черных",
    ",",
    "выше",
    "колен",
    ",",
    "валенках",
    "и",
    "в",
    "большой",
    "боярской",
    "шапке",
    ",",
    "сядет",
    "на",
    "диван",
    "и",
    "скажет",
    ";"
  ],
  "morphs": [
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "отец",
        "lexem": "отец",
        "tags": "OpencorporaTag('NOUN,anim,masc sing,nomn')"
      }
    ],
    [],
    [
      {
        "word": "огромный",
        "lexem": "огромный",
        "tags": "OpencorporaTag('ADJF,Qual masc,sing,nomn')"
      }
    ],
    [],
    [
      {
        "word": "толстый",
        "lexem": "толстый",
        "tags": "OpencorporaTag('ADJF,Qual masc,sing,nomn')"
      }
    ],
    [
      {
        "word": "от",
        "lexem": "от",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "медвежьей",
        "lexem": "медвежий",
        "tags": "OpencorporaTag('ADJF,Poss femn,sing,gent')"
      }
    ],
    [
      {
        "word": "шубы",
        "lexem": "шуба",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,gent')"
      },
      {
        "word": "шубы",
        "lexem": "шуба",
        "tags": "OpencorporaTag('NOUN,anim,femn sing,gent')"
      }
    ],
    [],
    [
      {
        "word": "надетой",
        "lexem": "надеть",
        "tags": "OpencorporaTag('PRTF,perf,tran,past,pssv femn,sing,gent')"
      }
    ],
    [
      {
        "word": "поверх",
        "lexem": "поверх",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "полушубка",
        "lexem": "полушубок",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,gent')"
      }
    ],
    [],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "чёрных",
        "lexem": "чёрный",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,gent')"
      },
      {
        "word": "чёрных",
        "lexem": "чёрный",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,accs')"
      },
      {
        "word": "чёрных",
        "lexem": "чёрный",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,loct')"
      }
    ],
    [],
    [
      {
        "word": "выше",
        "lexem": "высоко",
        "tags": "OpencorporaTag('COMP,Qual')"
      }
    ],
    [
      {
        "word": "колен",
        "lexem": "колено",
        "tags": "OpencorporaTag('NOUN,inan,neut plur,gent')"
      }
    ],
    [],
    [
      {
        "word": "валенках",
        "lexem": "валенок",
        "tags": "OpencorporaTag('NOUN,inan,masc plur,loct')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "большой",
        "lexem": "большой",
        "tags": "OpencorporaTag('ADJF,Qual femn,sing,datv')"
      }
    ],
    [
      {
        "word": "боярской",
        "lexem": "боярский",
        "tags": "OpencorporaTag('ADJF femn,sing,datv')"
      }
    ],
    [
      {
        "word": "шапке",
        "lexem": "шапка",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,datv')"
      }
    ],
    [],
    [
      {
        "word": "сядет",
        "lexem": "сесть",
        "tags": "OpencorporaTag('VERB,perf,intr sing,3per,futr,indc')"
      }
    ],
    [
      {
        "word": "на",
        "lexem": "на",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "диван",
        "lexem": "диван",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,accs')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "скажет",
        "lexem": "сказать",
        "tags": "OpencorporaTag('VERB,perf,tran sing,3per,futr,indc')"
      }
    ],
    []
  ],
  "synts": [
    [
      1,
      3,
      "опред",
      "отец",
      "огромный"
    ],
    [
      1,
      5,
      "опред",
      "отец",
      "толстый"
    ],
    [
      8,
      7,
      "опред",
      "шубы",
      "медвежьей"
    ],
    [
      8,
      10,
      "опред",
      "шубы",
      "надетой"
    ],
    [
      25,
      23,
      "опред",
      "шапке",
      "большой"
    ],
    [
      25,
      24,
      "опред",
      "шапке",
      "боярской"
    ],
    [
      6,
      8,
      "предл",
      "от",
      "шубы"
    ],
    [
      6,
      8,
      "предл",
      "от",
      "шубы"
    ],
    [
      11,
      12,
      "предл",
      "поверх",
      "полушубка"
    ],
    [
      14,
      15,
      "предл",
      "в",
      "чёрных"
    ],
    [
      14,
      15,
      "предл",
      "в",
      "чёрных"
    ],
    [
      14,
      15,
      "предл",
      "в",
      "чёрных"
    ],
    [
      22,
      25,
      "предл",
      "в",
      "шапке"
    ],
    [
      28,
      29,
      "предл",
      "на",
      "диван"
    ],
    [
      17,
      1,
      "предик",
      "выше",
      "отец"
    ],
    [
      27,
      6,
      "несобст-агент",
      "сядет",
      "от"
    ],
    [
      10,
      11,
      "1-компл",
      "надетой",
      "поверх"
    ],
    [
      10,
      14,
      "1-компл",
      "надетой",
      "в"
    ],
    [
      27,
      22,
      "1-компл",
      "сядет",
      "в"
    ],
    [
      27,
      28,
      "1-компл",
      "сядет",
      "на"
    ],
    [
      0,
      17,
      "соч-союзн",
      "и",
      "выше"
    ],
    [
      21,
      27,
      "соч-союзн",
      "и",
      "сядет"
    ],
    [
      30,
      31,
      "соч-союзн",
      "и",
      "скажет"
    ],
    [
      27,
      30,
      "сочин",
      "сядет",
      "и"
    ],
    [
      10,
      11,
      "обст",
      "надетой",
      "поверх"
    ],
    [
      27,
      28,
      "обст",
      "сядет",
      "на"
    ],
    [
      17,
      18,
      "сравнит",
      "выше",
      "колен"
    ],
    [
      17,
      20,
      "сравнит",
      "выше",
      "валенках"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/105.json
{
  "sentence": "Когда глаз привыкал к темноте, выступали вверху звезды и гребни гор, над деревней вырисовывались деревья, которых мы не замечали днем.",
  "tokens": [
    "Когда",
    "глаз",
    "привыкал",
    "к",
    "темноте",
    ",",
    "выступали",
    "вверху",
    "звезды",
    "и",
    "гребни",
    "гор",
    ",",
    "над",
    "деревней",
    "вырисовывались",
    "деревья",
    ",",
    "которых",
    "мы",
    "не",
    "замечали",
    "днем",
    "."
  ],
  "morphs": [
    [],
    [
      {
        "word": "глаз",
        "lexem": "глаз",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,nomn')"
      }
    ],
    [
      {
        "word": "привыкал",
        "lexem": "привыкать",
        "tags": "OpencorporaTag('VERB,impf,intr masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "к",
        "lexem": "к",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "темноте",
        "lexem": "темнота",
        "tags": "OpencorporaTag('NOUN,inan,femn,Sgtm sing,loct')"
      },
      {
        "word": "темноте",
        "lexem": "темнота",
        "tags": "OpencorporaTag('NOUN,inan,femn,Sgtm sing,datv')"
      }
    ],
    [],
    [
      {
        "word": "выступали",
        "lexem": "выступать",
        "tags": "OpencorporaTag('VERB,impf,intr plur,past,indc')"
      }
    ],
    [
      {
        "word": "вверху",
        "lexem": "вверху",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "звезды",
        "lexem": "звезда",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,gent')"
      },
      {
        "word": "звезды",
        "lexem": "звезда",
        "tags": "OpencorporaTag('NOUN,anim,femn sing,gent')"
      },
      {
        "word": "звёзды",
        "lexem": "звезда",
        "tags": "OpencorporaTag('NOUN,inan,femn plur,accs')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "гребни",
        "lexem": "гребень",
        "tags": "OpencorporaTag('NOUN,inan,masc plur,nomn')"
      },
      {
        "word": "гребни",
        "lexem": "гребнуть",
        "tags": "OpencorporaTag('VERB,perf,tran sing,impr,excl')"
      }
    ],
    [
      {
        "word": "гор",
        "lexem": "гора",
        "tags": "OpencorporaTag('NOUN,inan,femn plur,gent')"
      }
    ],
    [],
    [
      {
        "word": "над",
        "lexem": "над",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "деревней",
        "lexem": "деревня",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,ablt')"
      }
    ],
    [
      {
        "word": "вырисовывались",
        "lexem": "вырисовываться",
        "tags": "OpencorporaTag('VERB,impf,intr plur,past,indc')"
      }
    ],
    [
      {
        "word": "деревья",
        "lexem": "дерево",
        "tags": "OpencorporaTag('NOUN,inan,neut plur,accs')"
      }
    ],
    [],
    [
      {
        "word": "которых",
        "lexem": "который",
        "tags": "OpencorporaTag('ADJF,Subx,Apro,Anph plur,gent')"
      }
    ],
    [
      {
        "word": "мы",
        "lexem": "мы",
        "tags": "OpencorporaTag('NPRO,1per plur,nomn')"
      }
    ],
    [
      {
        "word": "не",
        "lexem": "не",
        "tags": "OpencorporaTag('PRCL')"
      }
    ],
    [
      {
        "word": "замечали",
        "lexem": "замечать",
        "tags": "OpencorporaTag('VERB,impf,tran plur,past,indc')"
      }
    ],
    [
      {
        "word": "днём",
        "lexem": "день",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,ablt')"
      },
      {
        "word": "днём",
        "lexem": "днём",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    []
  ],
  "synts": [
    [
      16,
      18,
      "квазиагент",
      "деревья",
      "которых"
    ],
    [
      15,
      14,
      "агент",
      "вырисовывались",
      "деревней"
    ],
    [
      21,
      22,
      "агент",
      "замечали",
      "днём"
    ],
    [
      3,
      4,
      "предл",
      "к",
      "темноте"
    ],
    [
      3,
      4,
      "предл",
      "к",
      "темноте"
    ],
    [
      7,
      8,
      "предл",
      "вверху",
      "звезды"
    ],
    [
      7,
      8,
      "предл",
      "вверху",
      "звезды"
    ],
    [
      7,
      8,
      "предл",
      "вверху",
      "звёзды"
    ],
    [
      21,
      20,
      "огранич",
      "замечали",
      "не"
    ],
    [
      10,
      11,
      "атриб",
      "гребни",
      "гор"
    ],
    [
      2,
      1,
      "предик",
      "привыкал",
      "глаз"
    ],
    [
      15,
      10,
      "предик",
      "вырисовывались",
      "гребни"
    ],
    [
      21,
      19,
      "предик",
      "замечали",
      "мы"
    ],
    [
      2,
      3,
      "1-компл",
      "привыкал",
      "к"
    ],
    [
      6,
      7,
      "1-компл",
      "выступали",
      "вверху"
    ],
    [
      15,
      13,
      "1-компл",
      "вырисовывались",
      "над"
    ],
    [
      15,
      16,
      "1-компл",
      "вырисовывались",
      "деревья"
    ],
    [
      21,
      22,
      "1-компл",
      "замечали",
      "днём"
    ],
    [
      2,
      6,
      "сочин",
      "привыкал",
      "выступали"
    ],
    [
      6,
      9,
      "сочин",
      "выступали",
      "и"
    ],
    [
      2,
      3,
      "обст",
      "привыкал",
      "к"
    ],
    [
      6,
      7,
      "обст",
      "выступали",
      "вверху"
    ],
    [
      21,
      22,
      "обст",
      "замечали",
      "днём"
    ],
    [
      16,
      21,
      "релят",
      "деревья",
      "замечали"
    ]
  ]
}
