=== vessellook/quiestioningBot/code/krasoteevo/tests/schema2.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "first version of schema of JSON format used by krasoteevo.ru",
  "type": "object",
  "properties": {
    "sentence": {
      "type": "string"
    },
    "tokens": {
      "type": "array",
      "description": "array of words",
      "items": {
        "type": "string"
      }
    },
    "morphs": {
      "type": "array",
      "description": "array of morph info lists",
      "items": {
        "type": "object",
        "description": "info about each token",
        "properties": {
          "index": {
            "type": "integer",
            "minimum": 0
          },
          "token": {
            "type": "string"
          },
          "lower": {
            "type": "string"
          },
          "homonyms": {
            "type": "array",
            "items": {
              "type": "object",
              "description": "morph info",
              "properties": {
                "index": {
                  "type": "integer",
                  "minimum": 0
                },
                "word": {
                  "type": "string"
                },
                "lexem": {
                  "type": "string"
                },
                "tags": {
                  "type": "string",
                  "pattern": "^OpencorporaTag\\('[A-Za-z ,0-9]+'\\)$"
                },
                "active": {
                  "type": "boolean"
                }
              }
            }
          },
          "banned_cases": {
            "type": "array"
          },
          "features": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "synts": {
      "type": "array",
      "description": "array of links between tokens",
      "items": {
        "type": "object",
        "properties": {
          "dep_type": {
            "type": "string"
          },
          "head": {
            "type": "string"
          },
          "dependent": {
            "type": "string"
          },
          "head_i": {
            "type": "integer",
            "minimum": 0
          },
          "dependent_i": {
            "type": "integer",
            "minimum": 0
          },
          "head_homonym_i": {
            "type": "integer",
            "minimum": 0
          },
          "dependent_homonym_i": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    }
  }
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/279.json
{
  "sentence": "— Дмитрий Прокофьич.",
  "tokens": [
    "—",
    "Дмитрий",
    "Прокофьич",
    "."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "—",
      "homonyms": [
        {
          "index": 0,
          "word": "—",
          "lexem": "—",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 1,
      "token": "Дмитрий",
      "homonyms": [
        {
          "index": 0,
          "word": "дмитрий",
          "lexem": "дмитрий",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 1,
          "word": "дмитрий",
          "lexem": "дмитрия",
          "tags": "S МН ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 2,
          "word": "дмитрий",
          "lexem": "дмитрия",
          "tags": "S МН ЖЕН ВИН ОД",
          "active": false
        }
      ]
    },
    {
      "index": 2,
      "token": "Прокофьич",
      "homonyms": [
        {
          "index": 0,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 1,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД МУЖ ИМ",
          "active": false
        },
        {
          "index": 2,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД МУЖ РОД",
          "active": false
        },
        {
          "index": 3,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД МУЖ ДАТ",
          "active": false
        },
        {
          "index": 4,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД МУЖ ВИН",
          "active": false
        },
        {
          "index": 5,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД МУЖ ТВОР",
          "active": false
        },
        {
          "index": 6,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД МУЖ ПР",
          "active": false
        },
        {
          "index": 7,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД ЖЕН ИМ",
          "active": false
        },
        {
          "index": 8,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД ЖЕН РОД",
          "active": false
        },
        {
          "index": 9,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД ЖЕН ДАТ",
          "active": false
        },
        {
          "index": 10,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД ЖЕН ВИН",
          "active": false
        },
        {
          "index": 11,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД ЖЕН ТВОР",
          "active": false
        },
        {
          "index": 12,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД ЖЕН ПР",
          "active": false
        },
        {
          "index": 13,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД СР ИМ",
          "active": false
        },
        {
          "index": 14,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД СР РОД",
          "active": false
        },
        {
          "index": 15,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД СР ДАТ",
          "active": false
        },
        {
          "index": 16,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД СР ВИН",
          "active": false
        },
        {
          "index": 17,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД СР ТВОР",
          "active": false
        },
        {
          "index": 18,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A ЕД СР ПР",
          "active": false
        },
        {
          "index": 19,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A МН ИМ",
          "active": false
        },
        {
          "index": 20,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A МН РОД",
          "active": false
        },
        {
          "index": 21,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A МН ДАТ",
          "active": false
        },
        {
          "index": 22,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A МН ВИН",
          "active": false
        },
        {
          "index": 23,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A МН ТВОР",
          "active": false
        },
        {
          "index": 24,
          "word": "прокофьич",
          "lexem": "прокофьич",
          "tags": "A МН ПР",
          "active": false
        }
      ]
    },
    {
      "index": 3,
      "token": ".",
      "homonyms": [
        {
          "index": 0,
          "word": ".",
          "lexem": ".",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": []
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/167.json
{
  "sentence": "Они вышли на улицу.",
  "tokens": [
    "Они",
    "вышли",
    "на",
    "улицу",
    "."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "Они",
      "homonyms": [
        {
          "index": 0,
          "word": "они",
          "lexem": "они",
          "tags": "S МН ИМ",
          "active": true
        }
      ]
    },
    {
      "index": 1,
      "token": "вышли",
      "homonyms": [
        {
          "index": 0,
          "word": "вышли",
          "lexem": "выйти",
          "tags": "V МН СОВ ПРОШ ИЗЪЯВ",
          "active": true
        },
        {
          "index": 1,
          "word": "вышли",
          "lexem": "выслать",
          "tags": "V ЕД СОВ ПОВ",
          "active": true
        }
      ]
    },
    {
      "index": 2,
      "token": "на",
      "homonyms": [
        {
          "index": 0,
          "word": "на",
          "lexem": "на",
          "tags": "PR",
          "active": true
        },
        {
          "index": 1,
          "word": "на",
          "lexem": "на",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "на",
          "lexem": "на",
          "tags": "INTJ",
          "active": false
        }
      ]
    },
    {
      "index": 3,
      "token": "улицу",
      "homonyms": [
        {
          "index": 0,
          "word": "улицу",
          "lexem": "улица",
          "tags": "S ЕД ЖЕН ВИН НЕОД",
          "active": true
        }
      ]
    },
    {
      "index": 4,
      "token": ".",
      "homonyms": [
        {
          "index": 0,
          "word": ".",
          "lexem": ".",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "предл",
      "head": "на",
      "dependent": "улицу",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 3,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "вышли",
      "dependent": "они",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 0,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "вышли",
      "dependent": "на",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 2,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "вышли",
      "dependent": "на",
      "head_i": 1,
      "head_homonym_i": 1,
      "dependent_i": 2,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "обст",
      "head": "вышли",
      "dependent": "на",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 2,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "обст",
      "head": "вышли",
      "dependent": "на",
      "head_i": 1,
      "head_homonym_i": 1,
      "dependent_i": 2,
      "dependent_homonym_i": 0
    }
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/337.json
{
  "sentence": "— Я уверена, что она достойная была девушка, — коротко заметила Авдотья Романовна.",
  "tokens": [
    "—",
    "Я",
    "уверена",
    ",",
    "что",
    "она",
    "достойная",
    "была",
    "девушка",
    ",",
    "—",
    "коротко",
    "заметила",
    "Авдотья",
    "Романовна",
    "."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "—",
      "homonyms": [
        {
          "index": 0,
          "word": "—",
          "lexem": "—",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 1,
      "token": "Я",
      "homonyms": [
        {
          "index": 0,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ИМ",
          "active": false
        },
        {
          "index": 1,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 2,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 3,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 4,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 5,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 6,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 7,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 8,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 9,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 10,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 11,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 12,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        },
        {
          "index": 13,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 14,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 15,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 16,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 17,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 18,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 19,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 20,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 21,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 22,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 23,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 24,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        }
      ]
    },
    {
      "index": 2,
      "token": "уверена",
      "homonyms": [
        {
          "index": 0,
          "word": "уверена",
          "lexem": "уверить",
          "tags": "V ПРИЧ КР ЕД ЖЕН",
          "active": true
        }
      ]
    },
    {
      "index": 3,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 4,
      "token": "что",
      "homonyms": [
        {
          "index": 0,
          "word": "что",
          "lexem": "что",
          "tags": "CONJ",
          "active": false
        },
        {
          "index": 1,
          "word": "что",
          "lexem": "что",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "что",
          "lexem": "что",
          "tags": "S ЕД СР ВИН",
          "active": true
        },
        {
          "index": 3,
          "word": "что",
          "lexem": "что",
          "tags": "S ЕД СР ИМ",
          "active": false
        },
        {
          "index": 4,
          "word": "что",
          "lexem": "что",
          "tags": "ADV",
          "active": false
        }
      ]
    },
    {
      "index": 5,
      "token": "она",
      "homonyms": [
        {
          "index": 0,
          "word": "она",
          "lexem": "она",
          "tags": "S ЕД ЖЕН ИМ",
          "active": true
        }
      ]
    },
    {
      "index": 6,
      "token": "достойная",
      "homonyms": [
        {
          "index": 0,
          "word": "достойная",
          "lexem": "достойный",
          "tags": "A ЕД ЖЕН ИМ",
          "active": true
        }
      ]
    },
    {
      "index": 7,
      "token": "была",
      "homonyms": [
        {
          "index": 0,
          "word": "была",
          "lexem": "быть",
          "tags": "V ЕД НЕСОВ ПРОШ ИЗЪЯВ",
          "active": true
        }
      ]
    },
    {
      "index": 8,
      "token": "девушка",
      "homonyms": [
        {
          "index": 0,
          "word": "девушка",
          "lexem": "девушка",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": true
        }
      ]
    },
    {
      "index": 9,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 10,
      "token": "—",
      "homonyms": [
        {
          "index": 0,
          "word": "—",
          "lexem": "—",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 11,
      "token": "коротко",
      "homonyms": [
        {
          "index": 0,
          "word": "коротко",
          "lexem": "коротко",
          "tags": "ADV",
          "active": false
        },
        {
          "index": 1,
          "word": "коротко",
          "lexem": "короткий",
          "tags": "A КР ЕД СР",
          "active": false
        }
      ]
    },
    {
      "index": 12,
      "token": "заметила",
      "homonyms": [
        {
          "index": 0,
          "word": "заметила",
          "lexem": "заметить",
          "tags": "V ЕД СОВ ПРОШ ИЗЪЯВ",
          "active": false
        }
      ]
    },
    {
      "index": 13,
      "token": "Авдотья",
      "homonyms": [
        {
          "index": 0,
          "word": "авдотья",
          "lexem": "авдотья",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": true
        }
      ]
    },
    {
      "index": 14,
      "token": "Романовна",
      "homonyms": [
        {
          "index": 0,
          "word": "романовна",
          "lexem": "романович",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": true
        }
      ]
    },
    {
      "index": 15,
      "token": ".",
      "homonyms": [
        {
          "index": 0,
          "word": ".",
          "lexem": ".",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "опред",
      "head": "она",
      "dependent": "достойная",
      "head_i": 5,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "аппоз",
      "head": "авдотья",
      "dependent": "романовна",
      "head_i": 13,
      "head_homonym_i": 0,
      "dependent_i": 14,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "была",
      "dependent": "она",
      "head_i": 7,
      "head_homonym_i": 0,
      "dependent_i": 5,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "была",
      "dependent": "девушка",
      "head_i": 7,
      "head_homonym_i": 0,
      "dependent_i": 8,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "была",
      "dependent": "авдотья",
      "head_i": 7,
      "head_homonym_i": 0,
      "dependent_i": 13,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "уверена",
      "dependent": "что",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 4,
      "dependent_homonym_i": 2
    }
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/31.json
{
  "sentence": "Ничего, пойду.",
  "tokens": [
    "Ничего",
    ",",
    "пойду",
    "."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "Ничего",
      "homonyms": [
        {
          "index": 0,
          "word": "ничего",
          "lexem": "ничего",
          "tags": "ADV",
          "active": false
        },
        {
          "index": 1,
          "word": "ничего",
          "lexem": "ничего",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "ничего",
          "lexem": "ничто",
          "tags": "S ЕД СР РОД",
          "active": false
        },
        {
          "index": 3,
          "word": "ничего",
          "lexem": "ничего",
          "tags": "S ЕД СР ИМ",
          "active": true
        }
      ]
    },
    {
      "index": 1,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 2,
      "token": "пойду",
      "homonyms": [
        {
          "index": 0,
          "word": "пойду",
          "lexem": "пойти",
          "tags": "V ЕД СОВ НЕПРОШ ИЗЪЯВ 1-Л",
          "active": true
        }
      ]
    },
    {
      "index": 3,
      "token": ".",
      "homonyms": [
        {
          "index": 0,
          "word": ".",
          "lexem": ".",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "предик",
      "head": "пойду",
      "dependent": "ничего",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 0,
      "dependent_homonym_i": 3
    }
  ]
}
