=== vessellook/quiestioningBot/code/krasoteevo/tests/schema2.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "first version of schema of JSON format used by krasoteevo.ru",
  "type": "object",
  "properties": {
    "sentence": {
      "type": "string"
    },
    "tokens": {
      "type": "array",
      "description": "array of words",
      "items": {
        "type": "string"
      }
    },
    "morphs": {
      "type": "array",
      "description": "array of morph info lists",
      "items": {
        "type": "object",
        "description": "info about each token",
        "properties": {
          "index": {
            "type": "integer",
            "minimum": 0
          },
          "token": {
            "type": "string"
          },
          "lower": {
            "type": "string"
          },
          "homonyms": {
            "type": "array",
            "items": {
              "type": "object",
              "description": "morph info",
              "properties": {
                "index": {
                  "type": "integer",
                  "minimum": 0
                },
                "word": {
                  "type": "string"
                },
                "lexem": {
                  "type": "string"
                },
                "tags": {
                  "type": "string",
                  "pattern": "^OpencorporaTag\\('[A-Za-z ,0-9]+'\\)$"
                },
                "active": {
                  "type": "boolean"
                }
              }
            }
          },
          "banned_cases": {
            "type": "array"
          },
          "features": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "synts": {
      "type": "array",
      "description": "array of links between tokens",
      "items": {
        "type": "object",
        "properties": {
          "dep_type": {
            "type": "string"
          },
          "head": {
            "type": "string"
          },
          "dependent": {
            "type": "string"
          },
          "head_i": {
            "type": "integer",
            "minimum": 0
          },
          "dependent_i": {
            "type": "integer",
            "minimum": 0
          },
          "head_homonym_i": {
            "type": "integer",
            "minimum": 0
          },
          "dependent_homonym_i": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    }
  }
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/385.json
{
  "sentence": "А впрочем, и я сам вчера...",
  "tokens": [
    "А",
    "впрочем",
    ",",
    "и",
    "я",
    "сам",
    "вчера",
    "..."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "А",
      "homonyms": [
        {
          "index": 0,
          "word": "а",
          "lexem": "а",
          "tags": "CONJ",
          "active": false
        },
        {
          "index": 1,
          "word": "а",
          "lexem": "а",
          "tags": "INTJ",
          "active": false
        },
        {
          "index": 2,
          "word": "а",
          "lexem": "а",
          "tags": "PART",
          "active": false
        },
        {
          "index": 3,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 4,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 5,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 6,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 7,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 8,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 9,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 10,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 11,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 12,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 13,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 14,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        },
        {
          "index": 15,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 16,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 17,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 18,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 19,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 20,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 21,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 22,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 23,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 24,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 25,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 26,
          "word": "а",
          "lexem": "а",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        }
      ]
    },
    {
      "index": 1,
      "token": "впрочем",
      "homonyms": [
        {
          "index": 0,
          "word": "впрочем",
          "lexem": "впрочем",
          "tags": "CONJ",
          "active": false
        }
      ]
    },
    {
      "index": 2,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 3,
      "token": "и",
      "homonyms": [
        {
          "index": 0,
          "word": "и",
          "lexem": "и",
          "tags": "CONJ",
          "active": true
        },
        {
          "index": 1,
          "word": "и",
          "lexem": "и",
          "tags": "PART",
          "active": false
        },
        {
          "index": 2,
          "word": "и",
          "lexem": "и",
          "tags": "INTJ",
          "active": false
        },
        {
          "index": 3,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 4,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 5,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 6,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 7,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 8,
          "word": "и",
          "lexem": "и",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 9,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 10,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 11,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 12,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 13,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 14,
          "word": "и",
          "lexem": "и",
          "tags": "S МН МУЖ ПР ОД",
          "active": false
        }
      ]
    },
    {
      "index": 4,
      "token": "я",
      "homonyms": [
        {
          "index": 0,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ИМ",
          "active": true
        }
      ]
    },
    {
      "index": 5,
      "token": "сам",
      "homonyms": [
        {
          "index": 0,
          "word": "сам",
          "lexem": "сам",
          "tags": "A ЕД МУЖ ИМ",
          "active": true
        },
        {
          "index": 1,
          "word": "сам",
          "lexem": "сам",
          "tags": "A ЕД МУЖ ВИН",
          "active": true
        }
      ]
    },
    {
      "index": 6,
      "token": "вчера",
      "homonyms": [
        {
          "index": 0,
          "word": "вчера",
          "lexem": "вчера",
          "tags": "ADV",
          "active": true
        }
      ]
    },
    {
      "index": 7,
      "token": "...",
      "homonyms": [
        {
          "index": 0,
          "word": "...",
          "lexem": "...",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "соч-союзн",
      "head": "и",
      "dependent": "я",
      "head_i": 3,
      "head_homonym_i": 0,
      "dependent_i": 4,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "соч-союзн",
      "head": "и",
      "dependent": "сам",
      "head_i": 3,
      "head_homonym_i": 0,
      "dependent_i": 5,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "соч-союзн",
      "head": "и",
      "dependent": "сам",
      "head_i": 3,
      "head_homonym_i": 0,
      "dependent_i": 5,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "обст",
      "head": "я",
      "dependent": "вчера",
      "head_i": 4,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    }
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/33.json
{
  "sentence": "Она будет мне в зад, пыль-то...",
  "tokens": [
    "Она",
    "будет",
    "мне",
    "в",
    "зад",
    ",",
    "пыль-то",
    "..."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "Она",
      "homonyms": [
        {
          "index": 0,
          "word": "она",
          "lexem": "она",
          "tags": "S ЕД ЖЕН ИМ",
          "active": true
        }
      ]
    },
    {
      "index": 1,
      "token": "будет",
      "homonyms": [
        {
          "index": 0,
          "word": "будет",
          "lexem": "быть",
          "tags": "V ЕД НЕСОВ НЕПРОШ ИЗЪЯВ 3-Л",
          "active": true
        }
      ]
    },
    {
      "index": 2,
      "token": "мне",
      "homonyms": [
        {
          "index": 0,
          "word": "мне",
          "lexem": "я",
          "tags": "S ЕД ДАТ",
          "active": true
        },
        {
          "index": 1,
          "word": "мне",
          "lexem": "я",
          "tags": "S ЕД ПР",
          "active": false
        }
      ]
    },
    {
      "index": 3,
      "token": "в",
      "homonyms": [
        {
          "index": 0,
          "word": "в",
          "lexem": "в",
          "tags": "PR",
          "active": true
        },
        {
          "index": 1,
          "word": "в",
          "lexem": "в",
          "tags": "S ЕД МУЖ РОД НЕОД",
          "active": false
        },
        {
          "index": 2,
          "word": "в",
          "lexem": "в",
          "tags": "S ЕД МУЖ ПР НЕОД",
          "active": false
        },
        {
          "index": 3,
          "word": "в",
          "lexem": "в",
          "tags": "S ЕД МУЖ ИМ НЕОД",
          "active": false
        },
        {
          "index": 4,
          "word": "в",
          "lexem": "в",
          "tags": "S ЕД МУЖ ДАТ НЕОД",
          "active": false
        },
        {
          "index": 5,
          "word": "в",
          "lexem": "в",
          "tags": "S ЕД МУЖ ВИН НЕОД",
          "active": false
        },
        {
          "index": 6,
          "word": "в",
          "lexem": "в",
          "tags": "S ЕД МУЖ ТВОР НЕОД",
          "active": false
        },
        {
          "index": 7,
          "word": "в",
          "lexem": "в",
          "tags": "S МН МУЖ ИМ НЕОД",
          "active": false
        },
        {
          "index": 8,
          "word": "в",
          "lexem": "в",
          "tags": "S МН МУЖ РОД НЕОД",
          "active": false
        },
        {
          "index": 9,
          "word": "в",
          "lexem": "в",
          "tags": "S МН МУЖ ДАТ НЕОД",
          "active": false
        },
        {
          "index": 10,
          "word": "в",
          "lexem": "в",
          "tags": "S МН МУЖ ВИН НЕОД",
          "active": false
        },
        {
          "index": 11,
          "word": "в",
          "lexem": "в",
          "tags": "S МН МУЖ ТВОР НЕОД",
          "active": false
        },
        {
          "index": 12,
          "word": "в",
          "lexem": "в",
          "tags": "S МН МУЖ ПР НЕОД",
          "active": false
        }
      ]
    },
    {
      "index": 4,
      "token": "зад",
      "homonyms": [
        {
          "index": 0,
          "word": "зад",
          "lexem": "зад",
          "tags": "S ЕД МУЖ ВИН НЕОД",
          "active": true
        },
        {
          "index": 1,
          "word": "зад",
          "lexem": "зад",
          "tags": "S ЕД МУЖ ИМ НЕОД",
          "active": true
        }
      ]
    },
    {
      "index": 5,
      "token": ",",
      "homonyms": [
        {
          "index": 0,
          "word": ",",
          "lexem": ",",
          "tags": "NID",
          "active": false
        }
      ]
    },
    {
      "index": 6,
      "token": "пыль-то",
      "homonyms": [
        {
          "index": 0,
          "word": "пыль-то",
          "lexem": "пыль-то",
          "tags": "S ЕД ЖЕН ИМ НЕОД",
          "active": true
        },
        {
          "index": 1,
          "word": "пыль-то",
          "lexem": "пыль-то",
          "tags": "S ЕД ЖЕН ВИН НЕОД",
          "active": true
        }
      ]
    },
    {
      "index": 7,
      "token": "...",
      "homonyms": [
        {
          "index": 0,
          "word": "...",
          "lexem": "...",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "предл",
      "head": "в",
      "dependent": "зад",
      "head_i": 3,
      "head_homonym_i": 0,
      "dependent_i": 4,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предл",
      "head": "в",
      "dependent": "зад",
      "head_i": 3,
      "head_homonym_i": 0,
      "dependent_i": 4,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "об-аппоз",
      "head": "зад",
      "dependent": "пыль-то",
      "head_i": 4,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "об-аппоз",
      "head": "зад",
      "dependent": "пыль-то",
      "head_i": 4,
      "head_homonym_i": 1,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "будет",
      "dependent": "она",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 0,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "будет",
      "dependent": "мне",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 2,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "1-компл",
      "head": "будет",
      "dependent": "в",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 3,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "сочин",
      "head": "зад",
      "dependent": "пыль-то",
      "head_i": 4,
      "head_homonym_i": 0,
      "dependent_i": 6,
      "dependent_homonym_i": 1
    },
    {
      "dep_type": "сочин",
      "head": "зад",
      "dependent": "пыль-то",
      "head_i": 4,
      "head_homonym_i": 1,
      "dependent_i": 6,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "обст",
      "head": "будет",
      "dependent": "в",
      "head_i": 1,
      "head_homonym_i": 0,
      "dependent_i": 3,
      "dependent_homonym_i": 0
    }
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples/263.json
{
  "sentence": "Я не удостоился лицезреть...",
  "tokens": [
    "Я",
    "не",
    "удостоился",
    "лицезреть",
    "..."
  ],
  "morphs": [
    {
      "index": 0,
      "token": "Я",
      "homonyms": [
        {
          "index": 0,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ИМ",
          "active": true
        },
        {
          "index": 1,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 2,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 3,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 4,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 5,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 6,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 7,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 8,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 9,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 10,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 11,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 12,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        },
        {
          "index": 13,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ИМ ОД",
          "active": false
        },
        {
          "index": 14,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ РОД ОД",
          "active": false
        },
        {
          "index": 15,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ДАТ ОД",
          "active": false
        },
        {
          "index": 16,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ВИН ОД",
          "active": false
        },
        {
          "index": 17,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ТВОР ОД",
          "active": false
        },
        {
          "index": 18,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД МУЖ ПР ОД",
          "active": false
        },
        {
          "index": 19,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ИМ ОД",
          "active": false
        },
        {
          "index": 20,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН РОД ОД",
          "active": false
        },
        {
          "index": 21,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ДАТ ОД",
          "active": false
        },
        {
          "index": 22,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ВИН ОД",
          "active": false
        },
        {
          "index": 23,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ТВОР ОД",
          "active": false
        },
        {
          "index": 24,
          "word": "я",
          "lexem": "я",
          "tags": "S ЕД ЖЕН ПР ОД",
          "active": false
        }
      ]
    },
    {
      "index": 1,
      "token": "не",
      "homonyms": [
        {
          "index": 0,
          "word": "не",
          "lexem": "не",
          "tags": "PART",
          "active": true
        }
      ]
    },
    {
      "index": 2,
      "token": "удостоился",
      "homonyms": [
        {
          "index": 0,
          "word": "удостоился",
          "lexem": "удостоиться",
          "tags": "V ЕД СОВ ПРОШ ИЗЪЯВ",
          "active": true
        }
      ]
    },
    {
      "index": 3,
      "token": "лицезреть",
      "homonyms": [
        {
          "index": 0,
          "word": "лицезреть",
          "lexem": "лицезреть",
          "tags": "V ИНФ НЕСОВ",
          "active": true
        }
      ]
    },
    {
      "index": 4,
      "token": "...",
      "homonyms": [
        {
          "index": 0,
          "word": "...",
          "lexem": "...",
          "tags": "NID",
          "active": false
        }
      ]
    }
  ],
  "synts": [
    {
      "dep_type": "огранич",
      "head": "удостоился",
      "dependent": "не",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 1,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "предик",
      "head": "удостоился",
      "dependent": "я",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 0,
      "dependent_homonym_i": 0
    },
    {
      "dep_type": "обст",
      "head": "удостоился",
      "dependent": "лицезреть",
      "head_i": 2,
      "head_homonym_i": 0,
      "dependent_i": 3,
      "dependent_homonym_i": 0
    }
  ]
}
