=== vessellook/quiestioningBot/code/krasoteevo/tests/schema1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "first version of schema of JSON format used by krasoteevo.ru",
  "type": "object",
  "properties": {
    "sentence": {
      "type": "string"
    },
    "tokens": {
      "type": "array",
      "description": "array of words",
      "items": {
        "type": "string"
      }
    },
    "morphs": {
      "type": "array",
      "description": "array of morph info lists",
      "items": {
        "type": "array",
        "description": "morph info list",
        "items": {
          "type": "object",
          "description": "morph info",
          "properties": {
            "word": {
              "type": "string"
            },
            "lexem": {
              "type": "string"
            },
            "tags": {
              "type": "string",
              "pattern": "^OpencorporaTag\\('[A-Za-z ,0-9]+'\\)$"
            }
          }
        }
      }
    },
    "synts": {
      "type": "array",
      "description": "array of links between tokens",
      "items": {
        "type": "array",
        "description": "link between tokens",
        "items": [
          {
            "type": "integer",
            "description": "source[main] token index"
          },
          {
            "type": "integer",
            "description": "target[dependent] token index"
          },
          {
            "type": "string",
            "description": "link's syntax type"
          },
          {
            "type": "string",
            "description": "source[main] token"
          },
          {
            "type": "string",
            "description": "target[dependent] token"
          }
        ]
      }
    }
  }
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/176.json
{
  "sentence": "Озабоченный и серьезный проснулся Разумихин на другой день в восьмом часу.",
  "tokens": [
    "Озабоченный",
    "и",
    "серьезный",
    "проснулся",
    "Разумихин",
    "на",
    "другой",
    "день",
    "в",
    "восьмом",
    "часу",
    "."
  ],
  "morphs": [
    [],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [],
    [
      {
        "word": "проснулся",
        "lexem": "проснуться",
        "tags": "OpencorporaTag('VERB,perf,intr masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "разумихин",
        "lexem": "разумихин",
        "tags": "OpencorporaTag('NOUN,anim,masc,Sgtm,Surn sing,nomn')"
      }
    ],
    [
      {
        "word": "на",
        "lexem": "на",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "другой",
        "lexem": "другой",
        "tags": "OpencorporaTag('ADJF,Subx,Apro inan,masc,sing,accs')"
      }
    ],
    [
      {
        "word": "день",
        "lexem": "день",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,accs')"
      }
    ],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [],
    [],
    []
  ],
  "synts": [
    [
      7,
      6,
      "опред",
      "день",
      "другой"
    ],
    [
      5,
      7,
      "предл",
      "на",
      "день"
    ],
    [
      7,
      8,
      "атриб",
      "день",
      "в"
    ],
    [
      3,
      4,
      "предик",
      "проснулся",
      "разумихин"
    ],
    [
      1,
      3,
      "соч-союзн",
      "и",
      "проснулся"
    ],
    [
      3,
      5,
      "обст",
      "проснулся",
      "на"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/193.json
{
  "sentence": "Кто он сравнительно с такою девушкой, — он, пьяный буян и вчерашний хвастун?",
  "tokens": [
    "Кто",
    "он",
    "сравнительно",
    "с",
    "такою",
    "девушкой",
    ",",
    "—",
    "он",
    ",",
    "пьяный",
    "буян",
    "и",
    "вчерашний",
    "хвастун",
    "?"
  ],
  "morphs": [
    [],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [
      {
        "word": "сравнительно",
        "lexem": "сравнительный",
        "tags": "OpencorporaTag('ADJS neut,sing')"
      }
    ],
    [
      {
        "word": "с",
        "lexem": "с",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "такою",
        "lexem": "такой",
        "tags": "OpencorporaTag('ADJF,Apro femn,sing,ablt,V-oy')"
      }
    ],
    [
      {
        "word": "девушкой",
        "lexem": "девушка",
        "tags": "OpencorporaTag('NOUN,anim,femn sing,ablt')"
      }
    ],
    [],
    [],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [],
    [
      {
        "word": "пьяный",
        "lexem": "пьяный",
        "tags": "OpencorporaTag('ADJF,Qual masc,sing,nomn')"
      }
    ],
    [
      {
        "word": "буян",
        "lexem": "буян",
        "tags": "OpencorporaTag('NOUN,anim,masc sing,nomn')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "вчерашний",
        "lexem": "вчерашний",
        "tags": "OpencorporaTag('ADJF masc,sing,nomn')"
      }
    ],
    [
      {
        "word": "хвастун",
        "lexem": "хвастун",
        "tags": "OpencorporaTag('NOUN,anim,masc sing,nomn')"
      }
    ],
    []
  ],
  "synts": [
    [
      11,
      10,
      "опред",
      "буян",
      "пьяный"
    ],
    [
      14,
      13,
      "опред",
      "хвастун",
      "вчерашний"
    ],
    [
      5,
      4,
      "опред",
      "девушкой",
      "такою"
    ],
    [
      3,
      5,
      "предл",
      "с",
      "девушкой"
    ],
    [
      8,
      11,
      "об-аппоз",
      "он",
      "буян"
    ],
    [
      2,
      1,
      "предик",
      "сравнительно",
      "он"
    ],
    [
      2,
      3,
      "1-компл",
      "сравнительно",
      "с"
    ],
    [
      12,
      14,
      "соч-союзн",
      "и",
      "хвастун"
    ],
    [
      11,
      12,
      "сочин",
      "буян",
      "и"
    ],
    [
      2,
      3,
      "обст",
      "сравнительно",
      "с"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/151.json
{
  "sentence": "Утром, когда я вышел в коридор, в нем было солнечно, душно, из уборных пахло мылом, одеколоном и всем, чем пахнет людный вагон утром.",
  "tokens": [
    "Утром",
    ",",
    "когда",
    "я",
    "вышел",
    "в",
    "коридор",
    ",",
    "в",
    "нем",
    "было",
    "солнечно",
    ",",
    "душно",
    ",",
    "из",
    "уборных",
    "пахло",
    "мылом",
    ",",
    "одеколоном",
    "и",
    "всем",
    ",",
    "чем",
    "пахнет",
    "людный",
    "вагон",
    "утром",
    "."
  ],
  "morphs": [
    [
      {
        "word": "утром",
        "lexem": "утро",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,ablt')"
      }
    ],
    [],
    [],
    [
      {
        "word": "я",
        "lexem": "я",
        "tags": "OpencorporaTag('NPRO,1per sing,nomn')"
      }
    ],
    [
      {
        "word": "вышел",
        "lexem": "выйти",
        "tags": "OpencorporaTag('VERB,perf,intr masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "коридор",
        "lexem": "коридор",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,nomn')"
      }
    ],
    [],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "нем",
        "lexem": "немой",
        "tags": "OpencorporaTag('ADJS,Qual masc,sing')"
      },
      {
        "word": "нём",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,loct,Af-p')"
      }
    ],
    [
      {
        "word": "было",
        "lexem": "быть",
        "tags": "OpencorporaTag('VERB,impf,intr neut,sing,past,indc')"
      }
    ],
    [
      {
        "word": "солнечно",
        "lexem": "солнечно",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [],
    [],
    [],
    [
      {
        "word": "из",
        "lexem": "из",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "уборных",
        "lexem": "уборная",
        "tags": "OpencorporaTag('NOUN,inan,femn plur,gent')"
      },
      {
        "word": "уборных",
        "lexem": "уборная",
        "tags": "OpencorporaTag('NOUN,inan,femn plur,loct')"
      }
    ],
    [
      {
        "word": "пахло",
        "lexem": "пахнуть",
        "tags": "OpencorporaTag('VERB,impf,intr neut,sing,past,indc')"
      }
    ],
    [
      {
        "word": "мылом",
        "lexem": "мыло",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,ablt')"
      }
    ],
    [],
    [
      {
        "word": "одеколоном",
        "lexem": "одеколон",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,ablt')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "всем",
        "lexem": "весь",
        "tags": "OpencorporaTag('ADJF,Subx,Apro neut,sing,ablt')"
      }
    ],
    [],
    [
      {
        "word": "чем",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,ablt')"
      }
    ],
    [
      {
        "word": "пахнет",
        "lexem": "пахнуть",
        "tags": "OpencorporaTag('VERB,impf,intr sing,3per,pres,indc')"
      },
      {
        "word": "пахнёт",
        "lexem": "пахнуть",
        "tags": "OpencorporaTag('VERB,perf,intr sing,3per,futr,indc')"
      }
    ],
    [
      {
        "word": "людный",
        "lexem": "людный",
        "tags": "OpencorporaTag('ADJF,Qual inan,masc,sing,accs')"
      }
    ],
    [
      {
        "word": "вагон",
        "lexem": "вагон",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,nomn')"
      }
    ],
    [
      {
        "word": "утром",
        "lexem": "утро",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,ablt')"
      }
    ],
    []
  ],
  "synts": [
    [
      24,
      22,
      "опред",
      "чем",
      "всем"
    ],
    [
      17,
      18,
      "агент",
      "пахло",
      "мылом"
    ],
    [
      25,
      24,
      "агент",
      "пахнет",
      "чем"
    ],
    [
      15,
      16,
      "предл",
      "из",
      "уборных"
    ],
    [
      15,
      16,
      "предл",
      "из",
      "уборных"
    ],
    [
      18,
      20,
      "об-аппоз",
      "мылом",
      "одеколоном"
    ],
    [
      27,
      28,
      "атриб",
      "вагон",
      "утром"
    ],
    [
      4,
      3,
      "предик",
      "вышел",
      "я"
    ],
    [
      9,
      6,
      "предик",
      "нем",
      "коридор"
    ],
    [
      25,
      27,
      "предик",
      "пахнет",
      "вагон"
    ],
    [
      4,
      0,
      "1-компл",
      "вышел",
      "утром"
    ],
    [
      4,
      5,
      "1-компл",
      "вышел",
      "в"
    ],
    [
      9,
      8,
      "1-компл",
      "нем",
      "в"
    ],
    [
      17,
      15,
      "1-компл",
      "пахло",
      "из"
    ],
    [
      17,
      18,
      "1-компл",
      "пахло",
      "мылом"
    ],
    [
      21,
      25,
      "соч-союзн",
      "и",
      "пахнет"
    ],
    [
      4,
      10,
      "сочин",
      "вышел",
      "было"
    ],
    [
      10,
      17,
      "сочин",
      "было",
      "пахло"
    ],
    [
      17,
      21,
      "сочин",
      "пахло",
      "и"
    ],
    [
      18,
      20,
      "сочин",
      "мылом",
      "одеколоном"
    ],
    [
      4,
      5,
      "обст",
      "вышел",
      "в"
    ],
    [
      10,
      11,
      "обст",
      "было",
      "солнечно"
    ],
    [
      0,
      4,
      "релят",
      "утром",
      "вышел"
    ],
    [
      10,
      9,
      "присвяз",
      "было",
      "нём"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/252.json
{
  "sentence": "— Кстати, имеешь ты какое-нибудь влияние на тех-то, на мать да сестру?",
  "tokens": [
    "—",
    "Кстати",
    ",",
    "имеешь",
    "ты",
    "какое-нибудь",
    "влияние",
    "на",
    "тех-то",
    ",",
    "на",
    "мать",
    "да",
    "сестру",
    "?"
  ],
  "morphs": [
    [],
    [],
    [],
    [
      {
        "word": "имеешь",
        "lexem": "иметь",
        "tags": "OpencorporaTag('VERB,impf,tran sing,2per,pres,indc')"
      }
    ],
    [
      {
        "word": "ты",
        "lexem": "ты",
        "tags": "OpencorporaTag('NPRO,2per sing,nomn')"
      }
    ],
    [
      {
        "word": "какое-нибудь",
        "lexem": "какой-нибудь",
        "tags": "OpencorporaTag('ADJF,Apro neut,sing,accs')"
      }
    ],
    [
      {
        "word": "влияние",
        "lexem": "влияние",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,accs')"
      }
    ],
    [
      {
        "word": "на",
        "lexem": "на",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "тех-то",
        "lexem": "тот-то",
        "tags": "OpencorporaTag('ADJF,Apro plur,gent')"
      },
      {
        "word": "тех-то",
        "lexem": "тот-то",
        "tags": "OpencorporaTag('ADJF,Apro anim,plur,accs')"
      },
      {
        "word": "тех-то",
        "lexem": "тот-то",
        "tags": "OpencorporaTag('ADJF,Apro plur,loct')"
      }
    ],
    [],
    [
      {
        "word": "на",
        "lexem": "на",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "мать",
        "lexem": "мать",
        "tags": "OpencorporaTag('NOUN,anim,femn sing,accs')"
      }
    ],
    [],
    [
      {
        "word": "сестру",
        "lexem": "сестра",
        "tags": "OpencorporaTag('NOUN,anim,femn sing,accs')"
      }
    ],
    []
  ],
  "synts": [
    [
      6,
      5,
      "опред",
      "влияние",
      "какое-нибудь"
    ],
    [
      10,
      11,
      "предл",
      "на",
      "мать"
    ],
    [
      3,
      4,
      "предик",
      "имеешь",
      "ты"
    ],
    [
      3,
      6,
      "1-компл",
      "имеешь",
      "влияние"
    ],
    [
      3,
      8,
      "1-компл",
      "имеешь",
      "тех-то"
    ],
    [
      3,
      8,
      "1-компл",
      "имеешь",
      "тех-то"
    ],
    [
      3,
      8,
      "1-компл",
      "имеешь",
      "тех-то"
    ],
    [
      3,
      10,
      "1-компл",
      "имеешь",
      "на"
    ],
    [
      3,
      13,
      "1-компл",
      "имеешь",
      "сестру"
    ],
    [
      3,
      7,
      "обст",
      "имеешь",
      "на"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/118.json
{
  "sentence": "— Мне кажется, — говорила она, — что он что-то подозревает, что он даже знает что-то, — может быть, прочитал какое-нибудь ваше письмо, подобрал ключ к моему столу...",
  "tokens": [
    "—",
    "Мне",
    "кажется",
    ",",
    "—",
    "говорила",
    "она",
    ",",
    "—",
    "что",
    "он",
    "что-то",
    "подозревает",
    ",",
    "что",
    "он",
    "даже",
    "знает",
    "что-то",
    ",",
    "—",
    "может",
    "быть",
    ",",
    "прочитал",
    "какое-нибудь",
    "ваше",
    "письмо",
    ",",
    "подобрал",
    "ключ",
    "к",
    "моему",
    "столу",
    "..."
  ],
  "morphs": [
    [],
    [
      {
        "word": "мне",
        "lexem": "я",
        "tags": "OpencorporaTag('NPRO,1per sing,datv')"
      }
    ],
    [
      {
        "word": "кажется",
        "lexem": "казаться",
        "tags": "OpencorporaTag('VERB,impf,intr sing,3per,pres,indc')"
      }
    ],
    [],
    [],
    [
      {
        "word": "говорила",
        "lexem": "говорить",
        "tags": "OpencorporaTag('VERB,impf,tran femn,sing,past,indc')"
      }
    ],
    [
      {
        "word": "она",
        "lexem": "она",
        "tags": "OpencorporaTag('NPRO,femn,3per,Anph sing,nomn')"
      }
    ],
    [],
    [],
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,accs')"
      }
    ],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [
      {
        "word": "что-то",
        "lexem": "что-то",
        "tags": "OpencorporaTag('NPRO,neut sing,nomn')"
      }
    ],
    [
      {
        "word": "подозревает",
        "lexem": "подозревать",
        "tags": "OpencorporaTag('VERB,impf,tran sing,3per,pres,indc')"
      }
    ],
    [],
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,accs')"
      }
    ],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [],
    [
      {
        "word": "знает",
        "lexem": "знать",
        "tags": "OpencorporaTag('VERB,impf,tran sing,3per,pres,indc')"
      }
    ],
    [
      {
        "word": "что-то",
        "lexem": "что-то",
        "tags": "OpencorporaTag('NPRO,neut sing,nomn')"
      }
    ],
    [],
    [],
    [
      {
        "word": "может",
        "lexem": "мочь",
        "tags": "OpencorporaTag('VERB,impf,intr sing,3per,pres,indc')"
      }
    ],
    [
      {
        "word": "быть",
        "lexem": "быть",
        "tags": "OpencorporaTag('INFN,impf,intr')"
      }
    ],
    [],
    [
      {
        "word": "прочитал",
        "lexem": "прочитать",
        "tags": "OpencorporaTag('VERB,perf,tran masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "какое-нибудь",
        "lexem": "какой-нибудь",
        "tags": "OpencorporaTag('ADJF,Apro neut,sing,accs')"
      }
    ],
    [
      {
        "word": "ваше",
        "lexem": "ваш",
        "tags": "OpencorporaTag('ADJF,Apro neut,sing,accs')"
      }
    ],
    [
      {
        "word": "письмо",
        "lexem": "письмо",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,nomn')"
      }
    ],
    [],
    [
      {
        "word": "подобрал",
        "lexem": "подобрать",
        "tags": "OpencorporaTag('VERB,perf,tran masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "ключ",
        "lexem": "ключ",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,accs')"
      }
    ],
    [
      {
        "word": "к",
        "lexem": "к",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "моему",
        "lexem": "мой",
        "tags": "OpencorporaTag('ADJF,Apro masc,sing,datv')"
      }
    ],
    [
      {
        "word": "столу",
        "lexem": "стол",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,datv')"
      }
    ],
    []
  ],
  "synts": [
    [
      33,
      32,
      "опред",
      "столу",
      "моему"
    ],
    [
      31,
      33,
      "предл",
      "к",
      "столу"
    ],
    [
      30,
      31,
      "атриб",
      "ключ",
      "к"
    ],
    [
      5,
      6,
      "предик",
      "говорила",
      "она"
    ],
    [
      12,
      11,
      "предик",
      "подозревает",
      "что-то"
    ],
    [
      17,
      15,
      "предик",
      "знает",
      "он"
    ],
    [
      21,
      18,
      "предик",
      "может",
      "что-то"
    ],
    [
      29,
      27,
      "предик",
      "подобрал",
      "письмо"
    ],
    [
      2,
      1,
      "1-компл",
      "кажется",
      "мне"
    ],
    [
      5,
      9,
      "1-компл",
      "говорила",
      "что"
    ],
    [
      12,
      14,
      "1-компл",
      "подозревает",
      "что"
    ],
    [
      29,
      30,
      "1-компл",
      "подобрал",
      "ключ"
    ],
    [
      9,
      10,
      "подч-союзн",
      "что",
      "он"
    ],
    [
      14,
      17,
      "подч-союзн",
      "что",
      "знает"
    ],
    [
      17,
      21,
      "сочин",
      "знает",
      "может"
    ],
    [
      24,
      29,
      "сочин",
      "прочитал",
      "подобрал"
    ],
    [
      21,
      22,
      "обст",
      "может",
      "быть"
    ],
    [
      2,
      33,
      "присвяз",
      "кажется",
      "столу"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/216.json
{
  "sentence": "Разумихин донес ему, что тот спит, как сурок.",
  "tokens": [
    "Разумихин",
    "донес",
    "ему",
    ",",
    "что",
    "тот",
    "спит",
    ",",
    "как",
    "сурок",
    "."
  ],
  "morphs": [
    [
      {
        "word": "разумихин",
        "lexem": "разумихин",
        "tags": "OpencorporaTag('NOUN,anim,masc,Sgtm,Surn sing,nomn')"
      }
    ],
    [
      {
        "word": "донёс",
        "lexem": "донести",
        "tags": "OpencorporaTag('VERB,perf,tran masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "ему",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,datv')"
      }
    ],
    [],
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,nomn')"
      }
    ],
    [
      {
        "word": "тот",
        "lexem": "тот",
        "tags": "OpencorporaTag('ADJF,Subx,Apro,Anph masc,sing,nomn')"
      }
    ],
    [
      {
        "word": "спит",
        "lexem": "спать",
        "tags": "OpencorporaTag('VERB,impf,intr sing,3per,pres,indc')"
      },
      {
        "word": "спит",
        "lexem": "спить",
        "tags": "OpencorporaTag('PRTS,perf,past,pssv masc,sing')"
      }
    ],
    [],
    [
      {
        "word": "как",
        "lexem": "как",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "сурок",
        "lexem": "сурок",
        "tags": "OpencorporaTag('NOUN,anim,masc sing,nomn')"
      }
    ],
    []
  ],
  "synts": [
    [
      1,
      0,
      "предик",
      "донёс",
      "разумихин"
    ],
    [
      6,
      4,
      "предик",
      "спит",
      "что"
    ],
    [
      1,
      2,
      "1-компл",
      "донёс",
      "ему"
    ],
    [
      6,
      5,
      "1-компл",
      "спит",
      "тот"
    ],
    [
      8,
      9,
      "подч-союзн",
      "как",
      "сурок"
    ],
    [
      8,
      9,
      "сравн-союзн",
      "как",
      "сурок"
    ],
    [
      2,
      6,
      "релят",
      "ему",
      "спит"
    ],
    [
      2,
      6,
      "релят",
      "ему",
      "спит"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/185.json
{
  "sentence": "Стало быть, есть же и в нем достоинства.",
  "tokens": [
    "Стало",
    "быть",
    ",",
    "есть",
    "же",
    "и",
    "в",
    "нем",
    "достоинства",
    "."
  ],
  "morphs": [
    [
      {
        "word": "стало",
        "lexem": "стать",
        "tags": "OpencorporaTag('VERB,perf,intr neut,sing,past,indc')"
      }
    ],
    [
      {
        "word": "быть",
        "lexem": "быть",
        "tags": "OpencorporaTag('INFN,impf,intr')"
      }
    ],
    [],
    [
      {
        "word": "есть",
        "lexem": "есть",
        "tags": "OpencorporaTag('INFN,impf,tran')"
      },
      {
        "word": "есть",
        "lexem": "быть",
        "tags": "OpencorporaTag('VERB,impf,intr sing,3per,pres,indc')"
      },
      {
        "word": "есть",
        "lexem": "быть",
        "tags": "OpencorporaTag('VERB,impf,intr plur,3per,pres,indc')"
      }
    ],
    [],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "нем",
        "lexem": "немой",
        "tags": "OpencorporaTag('ADJS,Qual masc,sing')"
      }
    ],
    [
      {
        "word": "достоинства",
        "lexem": "достоинство",
        "tags": "OpencorporaTag('NOUN,inan,neut plur,accs')"
      }
    ],
    []
  ],
  "synts": [
    [
      7,
      6,
      "1-компл",
      "нем",
      "в"
    ],
    [
      7,
      8,
      "1-компл",
      "нем",
      "достоинства"
    ],
    [
      5,
      7,
      "соч-союзн",
      "и",
      "нем"
    ],
    [
      1,
      3,
      "сочин",
      "быть",
      "есть"
    ],
    [
      0,
      1,
      "обст",
      "стало",
      "быть"
    ]
  ]
}
