=== vessellook/quiestioningBot/code/krasoteevo/tests/schema1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "first version of schema of JSON format used by krasoteevo.ru",
  "type": "object",
  "properties": {
    "sentence": {
      "type": "string"
    },
    "tokens": {
      "type": "array",
      "description": "array of words",
      "items": {
        "type": "string"
      }
    },
    "morphs": {
      "type": "array",
      "description": "array of morph info lists",
      "items": {
        "type": "array",
        "description": "morph info list",
        "items": {
          "type": "object",
          "description": "morph info",
          "properties": {
            "word": {
              "type": "string"
            },
            "lexem": {
              "type": "string"
            },
            "tags": {
              "type": "string",
              "pattern": "^OpencorporaTag\\('[A-Za-z ,0-9]+'\\)$"
            }
          }
        }
      }
    },
    "synts": {
      "type": "array",
      "description": "array of links between tokens",
      "items": {
        "type": "array",
        "description": "link between tokens",
        "items": [
          {
            "type": "integer",
            "description": "source[main] token index"
          },
          {
            "type": "integer",
            "description": "target[dependent] token index"
          },
          {
            "type": "string",
            "description": "link's syntax type"
          },
          {
            "type": "string",
            "description": "source[main] token"
          },
          {
            "type": "string",
            "description": "target[dependent] token"
          }
        ]
      }
    }
  }
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/337.json
{
  "sentence": "— Я уверена, что она достойная была девушка, — коротко заметила Авдотья Романовна.",
  "tokens": [
    "—",
    "Я",
    "уверена",
    ",",
    "что",
    "она",
    "достойная",
    "была",
    "девушка",
    ",",
    "—",
    "коротко",
    "заметила",
    "Авдотья",
    "Романовна",
    "."
  ],
  "morphs": [
    [],
    [],
    [
      {
        "word": "уверена",
        "lexem": "уверить",
        "tags": "OpencorporaTag('PRTS,perf,past,pssv femn,sing')"
      }
    ],
    [],
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,nomn')"
      }
    ],
    [
      {
        "word": "она",
        "lexem": "она",
        "tags": "OpencorporaTag('NPRO,femn,3per,Anph sing,nomn')"
      }
    ],
    [
      {
        "word": "достойная",
        "lexem": "достойный",
        "tags": "OpencorporaTag('ADJF,Qual femn,sing,nomn')"
      }
    ],
    [
      {
        "word": "была",
        "lexem": "быть",
        "tags": "OpencorporaTag('VERB,impf,intr femn,sing,past,indc')"
      }
    ],
    [
      {
        "word": "девушка",
        "lexem": "девушка",
        "tags": "OpencorporaTag('NOUN,anim,femn sing,nomn')"
      }
    ],
    [],
    [],
    [
      {
        "word": "коротко",
        "lexem": "коротко",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [
      {
        "word": "заметила",
        "lexem": "заметить",
        "tags": "OpencorporaTag('VERB,perf,tran femn,sing,past,indc')"
      }
    ],
    [
      {
        "word": "авдотья",
        "lexem": "авдотья",
        "tags": "OpencorporaTag('NOUN,anim,femn,Name sing,nomn')"
      }
    ],
    [
      {
        "word": "романовна",
        "lexem": "романович",
        "tags": "OpencorporaTag('NOUN,anim,femn,Patr sing,nomn')"
      }
    ],
    []
  ],
  "synts": [
    [
      5,
      6,
      "опред",
      "она",
      "достойная"
    ],
    [
      2,
      4,
      "предик",
      "уверена",
      "что"
    ],
    [
      7,
      5,
      "предик",
      "была",
      "она"
    ],
    [
      12,
      8,
      "предик",
      "заметила",
      "девушка"
    ],
    [
      4,
      7,
      "подч-союзн",
      "что",
      "была"
    ],
    [
      7,
      12,
      "сочин",
      "была",
      "заметила"
    ],
    [
      12,
      11,
      "обст",
      "заметила",
      "коротко"
    ],
    [
      7,
      13,
      "присвяз",
      "была",
      "авдотья"
    ],
    [
      7,
      14,
      "присвяз",
      "была",
      "романовна"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/315.json
{
  "sentence": "— Ведь он никого не любит; может, и никогда не полюбит, — отрезал Разумихин.",
  "tokens": [
    "—",
    "Ведь",
    "он",
    "никого",
    "не",
    "любит",
    ";",
    "может",
    ",",
    "и",
    "никогда",
    "не",
    "полюбит",
    ",",
    "—",
    "отрезал",
    "Разумихин",
    "."
  ],
  "morphs": [
    [],
    [],
    [
      {
        "word": "он",
        "lexem": "он",
        "tags": "OpencorporaTag('NPRO,masc,3per,Anph sing,nomn')"
      }
    ],
    [
      {
        "word": "никого",
        "lexem": "никто",
        "tags": "OpencorporaTag('NPRO sing,accs')"
      }
    ],
    [
      {
        "word": "не",
        "lexem": "не",
        "tags": "OpencorporaTag('PRCL')"
      }
    ],
    [
      {
        "word": "любит",
        "lexem": "любить",
        "tags": "OpencorporaTag('VERB,impf,tran sing,3per,pres,indc')"
      }
    ],
    [],
    [
      {
        "word": "может",
        "lexem": "мочь",
        "tags": "OpencorporaTag('VERB,impf,intr sing,3per,pres,indc')"
      }
    ],
    [],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "никогда",
        "lexem": "никогда",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [
      {
        "word": "не",
        "lexem": "не",
        "tags": "OpencorporaTag('PRCL')"
      }
    ],
    [
      {
        "word": "полюбит",
        "lexem": "полюбить",
        "tags": "OpencorporaTag('VERB,perf,tran sing,3per,futr,indc')"
      }
    ],
    [],
    [],
    [
      {
        "word": "отрезал",
        "lexem": "отрезать",
        "tags": "OpencorporaTag('VERB,impf,tran masc,sing,past,indc')"
      },
      {
        "word": "отрезал",
        "lexem": "отрезать",
        "tags": "OpencorporaTag('VERB,perf,tran masc,sing,past,indc')"
      }
    ],
    [
      {
        "word": "разумихин",
        "lexem": "разумихин",
        "tags": "OpencorporaTag('NOUN,anim,masc,Sgtm,Surn sing,nomn')"
      }
    ],
    []
  ],
  "synts": [
    [
      5,
      4,
      "огранич",
      "любит",
      "не"
    ],
    [
      12,
      11,
      "огранич",
      "полюбит",
      "не"
    ],
    [
      5,
      2,
      "предик",
      "любит",
      "он"
    ],
    [
      15,
      16,
      "предик",
      "отрезал",
      "разумихин"
    ],
    [
      15,
      16,
      "предик",
      "отрезал",
      "разумихин"
    ],
    [
      5,
      3,
      "1-компл",
      "любит",
      "никого"
    ],
    [
      9,
      12,
      "соч-союзн",
      "и",
      "полюбит"
    ],
    [
      5,
      7,
      "сочин",
      "любит",
      "может"
    ],
    [
      7,
      9,
      "сочин",
      "может",
      "и"
    ],
    [
      12,
      10,
      "обст",
      "полюбит",
      "никогда"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/92.json
{
  "sentence": "А там, во дворе, уже запрягают лошадей.",
  "tokens": [
    "А",
    "там",
    ",",
    "во",
    "дворе",
    ",",
    "уже",
    "запрягают",
    "лошадей",
    "."
  ],
  "morphs": [
    [
      {
        "word": "а",
        "lexem": "а",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [],
    [],
    [
      {
        "word": "во",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP Vpre')"
      }
    ],
    [
      {
        "word": "дворе",
        "lexem": "двор",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,loct')"
      }
    ],
    [],
    [
      {
        "word": "уже",
        "lexem": "узкий",
        "tags": "OpencorporaTag('COMP,Qual')"
      }
    ],
    [
      {
        "word": "запрягают",
        "lexem": "запрягать",
        "tags": "OpencorporaTag('VERB,impf,tran plur,3per,pres,indc')"
      }
    ],
    [
      {
        "word": "лошадей",
        "lexem": "лошадь",
        "tags": "OpencorporaTag('NOUN,anim,femn plur,accs')"
      }
    ],
    []
  ],
  "synts": [
    [
      3,
      4,
      "предл",
      "во",
      "дворе"
    ],
    [
      7,
      3,
      "несобст-агент",
      "запрягают",
      "во"
    ],
    [
      7,
      8,
      "1-компл",
      "запрягают",
      "лошадей"
    ],
    [
      0,
      6,
      "соч-союзн",
      "а",
      "уже"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/66.json
{
  "sentence": "Грусть, одиночество, скучные, одинаковые дни в чужой семье.",
  "tokens": [
    "Грусть",
    ",",
    "одиночество",
    ",",
    "скучные",
    ",",
    "одинаковые",
    "дни",
    "в",
    "чужой",
    "семье",
    "."
  ],
  "morphs": [
    [
      {
        "word": "грусть",
        "lexem": "грусть",
        "tags": "OpencorporaTag('NOUN,inan,femn,Sgtm sing,accs')"
      },
      {
        "word": "грусть",
        "lexem": "грусть",
        "tags": "OpencorporaTag('NOUN,inan,femn,Sgtm sing,nomn')"
      }
    ],
    [],
    [
      {
        "word": "одиночество",
        "lexem": "одиночество",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,nomn')"
      },
      {
        "word": "одиночество",
        "lexem": "одиночество",
        "tags": "OpencorporaTag('NOUN,inan,neut sing,accs')"
      }
    ],
    [],
    [
      {
        "word": "скучные",
        "lexem": "скучный",
        "tags": "OpencorporaTag('ADJF,Qual inan,plur,accs')"
      },
      {
        "word": "скучные",
        "lexem": "скучный",
        "tags": "OpencorporaTag('ADJF,Qual plur,nomn')"
      }
    ],
    [],
    [
      {
        "word": "одинаковые",
        "lexem": "одинаковый",
        "tags": "OpencorporaTag('ADJF,Qual plur,nomn')"
      },
      {
        "word": "одинаковые",
        "lexem": "одинаковый",
        "tags": "OpencorporaTag('ADJF,Qual inan,plur,accs')"
      }
    ],
    [
      {
        "word": "дни",
        "lexem": "день",
        "tags": "OpencorporaTag('NOUN,inan,masc plur,accs')"
      },
      {
        "word": "дни",
        "lexem": "день",
        "tags": "OpencorporaTag('NOUN,inan,masc plur,nomn')"
      }
    ],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "чужой",
        "lexem": "чужой",
        "tags": "OpencorporaTag('ADJF,Subx femn,sing,loct')"
      }
    ],
    [
      {
        "word": "семье",
        "lexem": "семья",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,loct')"
      },
      {
        "word": "семье",
        "lexem": "семья",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,datv')"
      }
    ],
    []
  ],
  "synts": [
    [
      10,
      9,
      "опред",
      "семье",
      "чужой"
    ],
    [
      8,
      10,
      "предл",
      "в",
      "семье"
    ],
    [
      8,
      10,
      "предл",
      "в",
      "семье"
    ],
    [
      7,
      8,
      "распред",
      "дни",
      "в"
    ],
    [
      7,
      8,
      "распред",
      "дни",
      "в"
    ],
    [
      0,
      2,
      "об-аппоз",
      "грусть",
      "одиночество"
    ],
    [
      0,
      2,
      "об-аппоз",
      "грусть",
      "одиночество"
    ],
    [
      0,
      2,
      "сочин",
      "грусть",
      "одиночество"
    ],
    [
      0,
      2,
      "сочин",
      "грусть",
      "одиночество"
    ],
    [
      4,
      6,
      "сочин",
      "скучные",
      "одинаковые"
    ],
    [
      4,
      6,
      "сочин",
      "скучные",
      "одинаковые"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/80.json
{
  "sentence": "И уже на лестнице, необыкновенно крутой и донельзя затоптанной, слышно, как много в ней народу, как буйно носятся половые и какой густой, горячий угар стоит повсюду.",
  "tokens": [
    "И",
    "уже",
    "на",
    "лестнице",
    ",",
    "необыкновенно",
    "крутой",
    "и",
    "донельзя",
    "затоптанной",
    ",",
    "слышно",
    ",",
    "как",
    "много",
    "в",
    "ней",
    "народу",
    ",",
    "как",
    "буйно",
    "носятся",
    "половые",
    "и",
    "какой",
    "густой",
    ",",
    "горячий",
    "угар",
    "стоит",
    "повсюду",
    "."
  ],
  "morphs": [
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "уже",
        "lexem": "узкий",
        "tags": "OpencorporaTag('COMP,Qual')"
      }
    ],
    [
      {
        "word": "на",
        "lexem": "на",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "лестнице",
        "lexem": "лестница",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,datv')"
      },
      {
        "word": "лестнице",
        "lexem": "лестница",
        "tags": "OpencorporaTag('NOUN,inan,femn sing,loct')"
      }
    ],
    [],
    [],
    [
      {
        "word": "крутой",
        "lexem": "крутой",
        "tags": "OpencorporaTag('ADJF,Qual femn,sing,gent')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "донельзя",
        "lexem": "донельзя",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [
      {
        "word": "затоптанной",
        "lexem": "затоптать",
        "tags": "OpencorporaTag('PRTF,perf,tran,past,pssv femn,sing,gent')"
      },
      {
        "word": "затоптанной",
        "lexem": "затоптать",
        "tags": "OpencorporaTag('PRTF,perf,tran,past,pssv femn,sing,ablt')"
      },
      {
        "word": "затоптанной",
        "lexem": "затоптать",
        "tags": "OpencorporaTag('PRTF,perf,tran,past,pssv femn,sing,loct')"
      }
    ],
    [],
    [],
    [],
    [
      {
        "word": "как",
        "lexem": "как",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "много",
        "lexem": "много",
        "tags": "OpencorporaTag('NUMR accs')"
      }
    ],
    [
      {
        "word": "в",
        "lexem": "в",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "ней",
        "lexem": "она",
        "tags": "OpencorporaTag('NPRO,femn,3per,Anph sing,loct,Af-p')"
      },
      {
        "word": "ней",
        "lexem": "она",
        "tags": "OpencorporaTag('NPRO,femn,3per,Anph sing,ablt,Af-p')"
      },
      {
        "word": "ней",
        "lexem": "она",
        "tags": "OpencorporaTag('NPRO,femn,3per,Anph sing,datv,Af-p')"
      },
      {
        "word": "ней",
        "lexem": "она",
        "tags": "OpencorporaTag('NPRO,femn,3per,Anph sing,gent,Infr,Af-p')"
      }
    ],
    [
      {
        "word": "народу",
        "lexem": "народ",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,datv')"
      },
      {
        "word": "народу",
        "lexem": "народ",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,gen2')"
      }
    ],
    [],
    [],
    [
      {
        "word": "буйно",
        "lexem": "буйно",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    [
      {
        "word": "носятся",
        "lexem": "носиться",
        "tags": "OpencorporaTag('VERB,impf,intr plur,3per,pres,indc')"
      }
    ],
    [
      {
        "word": "половые",
        "lexem": "половой",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,nomn')"
      }
    ],
    [
      {
        "word": "и",
        "lexem": "и",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [
      {
        "word": "какой",
        "lexem": "какой",
        "tags": "OpencorporaTag('ADJF,Apro masc,sing,nomn')"
      }
    ],
    [],
    [],
    [
      {
        "word": "горячий",
        "lexem": "горячий",
        "tags": "OpencorporaTag('ADJF,Qual masc,sing,nomn')"
      }
    ],
    [
      {
        "word": "угар",
        "lexem": "угар",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,nomn')"
      }
    ],
    [
      {
        "word": "стоит",
        "lexem": "стоить",
        "tags": "OpencorporaTag('VERB,impf,intr,Impe sing,pres,indc')"
      },
      {
        "word": "стоит",
        "lexem": "стоить",
        "tags": "OpencorporaTag('VERB,impf,tran sing,3per,pres,indc')"
      },
      {
        "word": "стоит",
        "lexem": "стоять",
        "tags": "OpencorporaTag('VERB,impf,intr sing,3per,pres,indc')"
      }
    ],
    [
      {
        "word": "повсюду",
        "lexem": "повсюду",
        "tags": "OpencorporaTag('ADVB')"
      }
    ],
    []
  ],
  "synts": [
    [
      28,
      27,
      "опред",
      "угар",
      "горячий"
    ],
    [
      28,
      24,
      "опред",
      "угар",
      "какой"
    ],
    [
      1,
      2,
      "колич-огран",
      "уже",
      "на"
    ],
    [
      2,
      3,
      "предл",
      "на",
      "лестнице"
    ],
    [
      2,
      3,
      "предл",
      "на",
      "лестнице"
    ],
    [
      15,
      16,
      "предл",
      "в",
      "ней"
    ],
    [
      15,
      16,
      "предл",
      "в",
      "ней"
    ],
    [
      15,
      16,
      "предл",
      "в",
      "ней"
    ],
    [
      15,
      16,
      "предл",
      "в",
      "ней"
    ],
    [
      21,
      22,
      "предик",
      "носятся",
      "половые"
    ],
    [
      29,
      28,
      "предик",
      "стоит",
      "угар"
    ],
    [
      9,
      14,
      "1-компл",
      "затоптанной",
      "много"
    ],
    [
      9,
      15,
      "1-компл",
      "затоптанной",
      "в"
    ],
    [
      9,
      17,
      "1-компл",
      "затоптанной",
      "народу"
    ],
    [
      9,
      17,
      "1-компл",
      "затоптанной",
      "народу"
    ],
    [
      0,
      1,
      "соч-союзн",
      "и",
      "уже"
    ],
    [
      7,
      21,
      "соч-союзн",
      "и",
      "носятся"
    ],
    [
      23,
      29,
      "соч-союзн",
      "и",
      "стоит"
    ],
    [
      21,
      23,
      "сочин",
      "носятся",
      "и"
    ],
    [
      1,
      2,
      "обст",
      "уже",
      "на"
    ],
    [
      9,
      8,
      "обст",
      "затоптанной",
      "донельзя"
    ],
    [
      21,
      20,
      "обст",
      "носятся",
      "буйно"
    ],
    [
      29,
      30,
      "обст",
      "стоит",
      "повсюду"
    ],
    [
      1,
      6,
      "сравнит",
      "уже",
      "крутой"
    ],
    [
      13,
      17,
      "сравн-союзн",
      "как",
      "народу"
    ],
    [
      13,
      17,
      "сравн-союзн",
      "как",
      "народу"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/206.json
{
  "sentence": "Да ни за что же на свете!",
  "tokens": [
    "Да",
    "ни",
    "за",
    "что",
    "же",
    "на",
    "свете",
    "!"
  ],
  "morphs": [
    [],
    [
      {
        "word": "ни",
        "lexem": "ни",
        "tags": "OpencorporaTag('CONJ')"
      }
    ],
    [],
    [
      {
        "word": "что",
        "lexem": "что",
        "tags": "OpencorporaTag('NPRO,neut sing,accs')"
      }
    ],
    [],
    [
      {
        "word": "на",
        "lexem": "на",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [
      {
        "word": "свете",
        "lexem": "свет",
        "tags": "OpencorporaTag('NOUN,inan,masc,Sgtm sing,loct')"
      }
    ],
    []
  ],
  "synts": [
    [
      5,
      6,
      "предл",
      "на",
      "свете"
    ],
    [
      1,
      3,
      "соч-союзн",
      "ни",
      "что"
    ]
  ]
}

=== vessellook/quiestioningBot/code/krasoteevo/examples_dir/83.json
{
  "sentence": "Сколько их кругом, этих мужиков, извозчиков, толстых купцов, худых барышников!",
  "tokens": [
    "Сколько",
    "их",
    "кругом",
    ",",
    "этих",
    "мужиков",
    ",",
    "извозчиков",
    ",",
    "толстых",
    "купцов",
    ",",
    "худых",
    "барышников",
    "!"
  ],
  "morphs": [
    [],
    [
      {
        "word": "их",
        "lexem": "их",
        "tags": "OpencorporaTag('ADJF,Fixd,Apro,Anph masc,sing,ablt')"
      }
    ],
    [
      {
        "word": "кругом",
        "lexem": "круг",
        "tags": "OpencorporaTag('NOUN,inan,masc sing,ablt')"
      },
      {
        "word": "кругом",
        "lexem": "кругом",
        "tags": "OpencorporaTag('PREP')"
      }
    ],
    [],
    [],
    [
      {
        "word": "мужиков",
        "lexem": "мужик",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,gent')"
      },
      {
        "word": "мужиков",
        "lexem": "мужик",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,accs')"
      }
    ],
    [],
    [
      {
        "word": "извозчиков",
        "lexem": "извозчик",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,gent')"
      },
      {
        "word": "извозчиков",
        "lexem": "извозчик",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,accs')"
      }
    ],
    [],
    [
      {
        "word": "толстых",
        "lexem": "толстый",
        "tags": "OpencorporaTag('ADJF,Qual plur,gent')"
      },
      {
        "word": "толстых",
        "lexem": "толстый",
        "tags": "OpencorporaTag('ADJF,Qual anim,plur,accs')"
      }
    ],
    [
      {
        "word": "купцов",
        "lexem": "купец",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,gent')"
      }
    ],
    [],
    [],
    [
      {
        "word": "барышников",
        "lexem": "барышник",
        "tags": "OpencorporaTag('NOUN,anim,masc plur,accs')"
      }
    ],
    []
  ],
  "synts": [
    [
      2,
      1,
      "опред",
      "кругом",
      "их"
    ],
    [
      2,
      5,
      "предл",
      "кругом",
      "мужиков"
    ],
    [
      2,
      5,
      "предл",
      "кругом",
      "мужиков"
    ],
    [
      5,
      7,
      "об-аппоз",
      "мужиков",
      "извозчиков"
    ],
    [
      5,
      7,
      "об-аппоз",
      "мужиков",
      "извозчиков"
    ],
    [
      7,
      13,
      "об-аппоз",
      "извозчиков",
      "барышников"
    ],
    [
      9,
      10,
      "атриб",
      "толстых",
      "купцов"
    ],
    [
      9,
      10,
      "атриб",
      "толстых",
      "купцов"
    ],
    [
      5,
      7,
      "сочин",
      "мужиков",
      "извозчиков"
    ],
    [
      5,
      7,
      "сочин",
      "мужиков",
      "извозчиков"
    ]
  ]
}
